// bridge.m — GOX iOS bridge implementation
// Auto-generated by gox. Do not edit.

#import <UIKit/UIKit.h>

// Exported from the Go static library
extern const char* GoxGetTree(void);
extern void GoxFreeString(const char* s);

// --- Color parsing ---

static UIColor* parseColor(NSString *hex) {
    if (!hex || [hex length] == 0 || [hex characterAtIndex:0] != '#') {
        return [UIColor blackColor];
    }

    NSString *str = [hex substringFromIndex:1];
    unsigned long len = [str length];
    unsigned int r = 0, g = 0, b = 0, a = 255;

    if (len == 3) {
        unsigned int vals[3];
        for (int i = 0; i < 3; i++) {
            NSString *ch = [str substringWithRange:NSMakeRange(i, 1)];
            [[NSScanner scannerWithString:ch] scanHexInt:&vals[i]];
            vals[i] = vals[i] * 17;
        }
        r = vals[0]; g = vals[1]; b = vals[2];
    } else if (len == 6) {
        unsigned int val;
        [[NSScanner scannerWithString:str] scanHexInt:&val];
        r = (val >> 16) & 0xFF;
        g = (val >> 8) & 0xFF;
        b = val & 0xFF;
    } else if (len == 8) {
        unsigned int val;
        [[NSScanner scannerWithString:str] scanHexInt:&val];
        r = (val >> 24) & 0xFF;
        g = (val >> 16) & 0xFF;
        b = (val >> 8) & 0xFF;
        a = val & 0xFF;
    }

    return [UIColor colorWithRed:r/255.0 green:g/255.0 blue:b/255.0 alpha:a/255.0];
}

// --- Style application ---

static void applyStyle(UIView *view, NSDictionary *style, BOOL isText) {
    if (!style) return;

    NSString *bgColor = style[@"BackgroundColor"];
    if (bgColor && [bgColor length] > 0) {
        view.backgroundColor = parseColor(bgColor);
    }

    NSNumber *opacity = style[@"Opacity"];
    if (opacity && [opacity doubleValue] > 0) {
        view.alpha = [opacity doubleValue];
    }

    NSNumber *borderRadius = style[@"BorderRadius"];
    if (borderRadius && [borderRadius doubleValue] > 0) {
        view.layer.cornerRadius = [borderRadius doubleValue];
        view.clipsToBounds = YES;
    }

    if (isText && [view isKindOfClass:[UILabel class]]) {
        UILabel *label = (UILabel *)view;

        NSNumber *fontSize = style[@"FontSize"];
        NSString *fontWeight = style[@"FontWeight"];
        CGFloat size = (fontSize && [fontSize doubleValue] > 0) ? [fontSize doubleValue] : 17.0;

        if (fontWeight && [fontWeight length] > 0) {
            UIFontWeight weight = UIFontWeightRegular;
            if ([fontWeight isEqualToString:@"bold"] || [fontWeight isEqualToString:@"700"]) {
                weight = UIFontWeightBold;
            } else if ([fontWeight isEqualToString:@"600"]) {
                weight = UIFontWeightSemibold;
            } else if ([fontWeight isEqualToString:@"500"]) {
                weight = UIFontWeightMedium;
            } else if ([fontWeight isEqualToString:@"300"]) {
                weight = UIFontWeightLight;
            }
            label.font = [UIFont systemFontOfSize:size weight:weight];
        } else if (fontSize && [fontSize doubleValue] > 0) {
            label.font = [UIFont systemFontOfSize:size];
        }

        NSString *color = style[@"Color"];
        if (color && [color length] > 0) {
            label.textColor = parseColor(color);
        }

        NSString *textAlign = style[@"TextAlign"];
        if (textAlign && [textAlign length] > 0) {
            if ([textAlign isEqualToString:@"center"]) {
                label.textAlignment = NSTextAlignmentCenter;
            } else if ([textAlign isEqualToString:@"right"]) {
                label.textAlignment = NSTextAlignmentRight;
            }
        }
    }
}

// --- View tree builder ---
// Node types: 0=element, 1=text, 2=fragment

static UIView* buildViewTree(NSDictionary *node) {
    if (!node) return nil;

    NSNumber *typeNum = node[@"type"];
    int nodeType = [typeNum intValue];

    NSString *tag = node[@"tag"];
    NSArray *children = node[@"children"];
    NSDictionary *props = node[@"props"];

    NSLog(@"GOX: Building node type=%d tag=%@", nodeType, tag);

    // Text node (type 1) — raw text, shouldn't appear at top level normally
    if (nodeType == 1) {
        UILabel *label = [[UILabel alloc] init];
        label.translatesAutoresizingMaskIntoConstraints = NO;
        label.text = node[@"text"];
        label.numberOfLines = 0;
        return label;
    }

    // Fragment (type 2)
    if (nodeType == 2) {
        if ([children count] == 1) {
            return buildViewTree(children[0]);
        }
        UIStackView *stack = [[UIStackView alloc] init];
        stack.translatesAutoresizingMaskIntoConstraints = NO;
        stack.axis = UILayoutConstraintAxisVertical;
        stack.spacing = 0;
        for (NSDictionary *child in children) {
            UIView *childView = buildViewTree(child);
            if (childView) {
                [stack addArrangedSubview:childView];
            }
        }
        return stack;
    }

    // Element (type 0)
    BOOL isText = [tag isEqualToString:@"Text"];

    if (isText) {
        // Collect text content from children
        NSMutableString *text = [NSMutableString string];
        for (NSDictionary *child in children) {
            NSNumber *childType = child[@"type"];
            if ([childType intValue] == 1) {
                NSString *t = child[@"text"];
                if (t) [text appendString:t];
            }
        }

        NSLog(@"GOX: Creating label with text: %@", text);

        UILabel *label = [[UILabel alloc] init];
        label.translatesAutoresizingMaskIntoConstraints = NO;
        label.text = text;
        label.numberOfLines = 0;

        NSDictionary *style = props[@"style"];
        applyStyle(label, style, YES);

        return label;
    }

    // Generic view container — use UIStackView for automatic vertical layout
    NSDictionary *style = props[@"style"];
    CGFloat padding = 0;
    if (style) {
        NSNumber *p = style[@"Padding"];
        if (p) padding = [p doubleValue];
    }

    UIStackView *stack = [[UIStackView alloc] init];
    stack.translatesAutoresizingMaskIntoConstraints = NO;
    stack.axis = UILayoutConstraintAxisVertical;
    stack.spacing = 8;
    stack.alignment = UIStackViewAlignmentLeading;
    stack.layoutMarginsRelativeArrangement = YES;
    stack.layoutMargins = UIEdgeInsetsMake(padding, padding, padding, padding);

    applyStyle(stack, style, NO);

    for (NSDictionary *child in children) {
        UIView *childView = buildViewTree(child);
        if (childView) {
            [stack addArrangedSubview:childView];
        }
    }

    NSLog(@"GOX: Created container with %lu children", (unsigned long)[children count]);

    return stack;
}

// --- App lifecycle ---

@interface GoxAppDelegate : UIResponder <UIApplicationDelegate>
@property (nonatomic, strong) UIWindow *window;
@end

@implementation GoxAppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

    self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
    self.window.backgroundColor = [UIColor whiteColor];

    UIViewController *vc = [[UIViewController alloc] init];
    vc.view.backgroundColor = [UIColor whiteColor];
    self.window.rootViewController = vc;
    [self.window makeKeyAndVisible];

    // Get the view tree from Go
    const char *json = GoxGetTree();
    NSLog(@"GOX: Got tree JSON length: %lu", json ? strlen(json) : 0);

    if (json) {
        NSData *data = [NSData dataWithBytes:json length:strlen(json)];
        GoxFreeString(json);

        NSError *error = nil;
        NSDictionary *tree = [NSJSONSerialization JSONObjectWithData:data
                                                            options:0
                                                              error:&error];
        if (tree && !error) {
            UIView *rootView = buildViewTree(tree);
            if (rootView) {
                [vc.view addSubview:rootView];

                [NSLayoutConstraint activateConstraints:@[
                    [rootView.topAnchor constraintEqualToAnchor:vc.view.safeAreaLayoutGuide.topAnchor],
                    [rootView.leadingAnchor constraintEqualToAnchor:vc.view.safeAreaLayoutGuide.leadingAnchor],
                    [rootView.trailingAnchor constraintEqualToAnchor:vc.view.safeAreaLayoutGuide.trailingAnchor],
                ]];

                NSLog(@"GOX: Root view added to screen");
            }
        } else {
            NSLog(@"GOX: JSON parse error: %@", error);
        }
    }

    return YES;
}

@end

int main(int argc, char * argv[]) {
    @autoreleasepool {
        return UIApplicationMain(argc, argv, nil, NSStringFromClass([GoxAppDelegate class]));
    }
}
