// bridge.m — GOX iOS bridge implementation
// Auto-generated by gox. Do not edit.
//
// Architecture:
//   1. AppDelegate gets screen dimensions + safe area insets
//   2. Calls GoxGetLayout() (exported from Go) with screen info
//   3. Go runs Yoga layout engine, returns flat array of positioned frames
//   4. This code creates UIKit views and positions them with view.frame
//
// No UIStackView. No Auto Layout. All layout is computed by Yoga in Go.

#import <UIKit/UIKit.h>

// Exported from the Go static library
extern const char* GoxGetLayout(double w, double h, double safeT, double safeR, double safeB, double safeL);
extern void GoxHandleEvent(int viewID);
extern const char* GoxRerender(void);
extern void GoxFreeString(const char* s);

// Forward declaration
static void buildUI(UIViewController *vc, NSArray *frames);

// Global VC reference for re-renders
static UIViewController *goxViewController = nil;

// --- Color parsing ---

static UIColor* parseColor(NSString *hex) {
    if (!hex || [hex length] == 0 || [hex characterAtIndex:0] != '#') {
        return nil;
    }

    NSString *str = [hex substringFromIndex:1];
    unsigned long len = [str length];
    unsigned int r = 0, g = 0, b = 0, a = 255;

    if (len == 3) {
        unsigned int vals[3];
        for (int i = 0; i < 3; i++) {
            NSString *ch = [str substringWithRange:NSMakeRange(i, 1)];
            [[NSScanner scannerWithString:ch] scanHexInt:&vals[i]];
            vals[i] = vals[i] * 17;
        }
        r = vals[0]; g = vals[1]; b = vals[2];
    } else if (len == 6) {
        unsigned int val;
        [[NSScanner scannerWithString:str] scanHexInt:&val];
        r = (val >> 16) & 0xFF;
        g = (val >> 8) & 0xFF;
        b = val & 0xFF;
    } else if (len == 8) {
        unsigned int val;
        [[NSScanner scannerWithString:str] scanHexInt:&val];
        r = (val >> 24) & 0xFF;
        g = (val >> 16) & 0xFF;
        b = (val >> 8) & 0xFF;
        a = val & 0xFF;
    }

    return [UIColor colorWithRed:r/255.0 green:g/255.0 blue:b/255.0 alpha:a/255.0];
}

// --- View creation by tag ---

static UIView* createViewForTag(NSString *tag, NSDictionary *props) {
    if ([tag isEqualToString:@"Text"]) {
        UILabel *label = [[UILabel alloc] init];
        label.numberOfLines = 0;
        return label;
    }

    if ([tag isEqualToString:@"_text"]) {
        // Raw text node — shouldn't appear as a top-level view normally
        UILabel *label = [[UILabel alloc] init];
        label.numberOfLines = 0;
        return label;
    }

    if ([tag isEqualToString:@"Button"]) {
        UIButton *button = [UIButton buttonWithType:UIButtonTypeSystem];
        return button;
    }

    if ([tag isEqualToString:@"TextInput"]) {
        UITextField *field = [[UITextField alloc] init];
        field.borderStyle = UITextBorderStyleRoundedRect;

        NSString *placeholder = props[@"placeholder"];
        if (placeholder) field.placeholder = placeholder;

        NSString *value = props[@"value"];
        if (value) field.text = value;

        NSNumber *secure = props[@"secure"];
        if (secure && [secure boolValue]) field.secureTextEntry = YES;

        NSString *kbType = props[@"keyboardType"];
        if ([kbType isEqualToString:@"email"]) field.keyboardType = UIKeyboardTypeEmailAddress;
        else if ([kbType isEqualToString:@"numeric"]) field.keyboardType = UIKeyboardTypeNumberPad;
        else if ([kbType isEqualToString:@"phone"]) field.keyboardType = UIKeyboardTypePhonePad;
        else if ([kbType isEqualToString:@"url"]) field.keyboardType = UIKeyboardTypeURL;

        return field;
    }

    if ([tag isEqualToString:@"Image"]) {
        UIImageView *imageView = [[UIImageView alloc] init];
        imageView.contentMode = UIViewContentModeScaleAspectFit;
        imageView.clipsToBounds = YES;

        NSString *contentMode = props[@"contentMode"];
        if ([contentMode isEqualToString:@"cover"]) imageView.contentMode = UIViewContentModeScaleAspectFill;
        else if ([contentMode isEqualToString:@"stretch"]) imageView.contentMode = UIViewContentModeScaleToFill;
        else if ([contentMode isEqualToString:@"center"]) imageView.contentMode = UIViewContentModeCenter;

        // Async image loading
        NSString *src = props[@"src"];
        if (src && [src length] > 0) {
            if ([src hasPrefix:@"http://"] || [src hasPrefix:@"https://"]) {
                dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
                    NSURL *url = [NSURL URLWithString:src];
                    NSData *data = [NSData dataWithContentsOfURL:url];
                    if (data) {
                        UIImage *image = [UIImage imageWithData:data];
                        dispatch_async(dispatch_get_main_queue(), ^{
                            imageView.image = image;
                        });
                    }
                });
            } else {
                imageView.image = [UIImage imageNamed:src];
            }
        }

        return imageView;
    }

    if ([tag isEqualToString:@"Switch"]) {
        UISwitch *sw = [[UISwitch alloc] init];
        NSNumber *value = props[@"value"];
        if (value) sw.on = [value boolValue];
        NSNumber *disabled = props[@"disabled"];
        if (disabled && [disabled boolValue]) sw.enabled = NO;
        return sw;
    }

    if ([tag isEqualToString:@"ScrollView"]) {
        UIScrollView *scrollView = [[UIScrollView alloc] init];
        return scrollView;
    }

    // Default: plain UIView (View, SafeArea, Row, Column, Fragment, etc.)
    UIView *v = [[UIView alloc] init];
    v.clipsToBounds = YES;
    return v;
}

// --- Visual style application (no layout — Yoga handles that) ---

static void applyVisualStyle(UIView *view, NSDictionary *props) {
    if (!props) return;

    NSDictionary *style = props[@"style"];
    if (!style) return;

    // Background color
    NSString *bgColor = style[@"BackgroundColor"];
    if (bgColor && [bgColor length] > 0) {
        UIColor *color = parseColor(bgColor);
        if (color) view.backgroundColor = color;
    }

    // Opacity
    NSNumber *opacity = style[@"Opacity"];
    if (opacity && [opacity doubleValue] > 0) {
        view.alpha = [opacity doubleValue];
    }

    // Border radius
    NSNumber *borderRadius = style[@"BorderRadius"];
    if (borderRadius && [borderRadius doubleValue] > 0) {
        view.layer.cornerRadius = [borderRadius doubleValue];
        view.clipsToBounds = YES;
    }

    // Border
    NSNumber *borderWidth = style[@"BorderWidth"];
    if (borderWidth && [borderWidth doubleValue] > 0) {
        view.layer.borderWidth = [borderWidth doubleValue];
    }
    NSString *borderColor = style[@"BorderColor"];
    if (borderColor && [borderColor length] > 0) {
        UIColor *bc = parseColor(borderColor);
        if (bc) view.layer.borderColor = bc.CGColor;
    }

    // Shadow
    NSString *shadowColor = style[@"ShadowColor"];
    if (shadowColor && [shadowColor length] > 0) {
        UIColor *sc = parseColor(shadowColor);
        if (sc) {
            view.layer.shadowColor = sc.CGColor;
            view.layer.shadowOffset = CGSizeMake(
                [style[@"ShadowOffsetX"] doubleValue],
                [style[@"ShadowOffsetY"] doubleValue]
            );
            view.layer.shadowRadius = [style[@"ShadowRadius"] doubleValue];
            view.layer.shadowOpacity = [style[@"ShadowOpacity"] floatValue];
        }
    }

    // Text-specific styles
    if ([view isKindOfClass:[UILabel class]]) {
        UILabel *label = (UILabel *)view;

        NSNumber *fontSize = style[@"FontSize"];
        NSString *fontWeight = style[@"FontWeight"];
        CGFloat size = (fontSize && [fontSize doubleValue] > 0) ? [fontSize doubleValue] : 17.0;

        if (fontWeight && [fontWeight length] > 0) {
            UIFontWeight weight = UIFontWeightRegular;
            if ([fontWeight isEqualToString:@"bold"] || [fontWeight isEqualToString:@"700"]) weight = UIFontWeightBold;
            else if ([fontWeight isEqualToString:@"600"]) weight = UIFontWeightSemibold;
            else if ([fontWeight isEqualToString:@"500"]) weight = UIFontWeightMedium;
            else if ([fontWeight isEqualToString:@"300"]) weight = UIFontWeightLight;
            label.font = [UIFont systemFontOfSize:size weight:weight];
        } else if (fontSize && [fontSize doubleValue] > 0) {
            label.font = [UIFont systemFontOfSize:size];
        }

        NSString *color = style[@"Color"];
        if (color && [color length] > 0) {
            UIColor *c = parseColor(color);
            if (c) label.textColor = c;
        }

        NSString *textAlign = style[@"TextAlign"];
        if ([textAlign isEqualToString:@"center"]) label.textAlignment = NSTextAlignmentCenter;
        else if ([textAlign isEqualToString:@"right"]) label.textAlignment = NSTextAlignmentRight;
    }
}

// --- Set text content on a view ---

static void setTextContent(UIView *view, NSString *text, NSDictionary *props) {
    if ([view isKindOfClass:[UILabel class]]) {
        ((UILabel *)view).text = text;
    } else if ([view isKindOfClass:[UIButton class]]) {
        [(UIButton *)view setTitle:text forState:UIControlStateNormal];

        // Apply child text styling to button
        NSDictionary *style = props[@"style"];
        if (style) {
            NSString *color = style[@"Color"];
            if (color && [color length] > 0) {
                UIColor *c = parseColor(color);
                if (c) [(UIButton *)view setTitleColor:c forState:UIControlStateNormal];
            }
            NSNumber *fontSize = style[@"FontSize"];
            if (fontSize && [fontSize doubleValue] > 0) {
                ((UIButton *)view).titleLabel.font = [UIFont systemFontOfSize:[fontSize doubleValue]];
            }
        }
    }
}

// --- Event handling ---

// Helper to handle button taps — stores the view ID and calls Go
@interface GoxEventHandler : NSObject
@property (nonatomic, assign) int viewID;
- (void)handleTap;
@end

@implementation GoxEventHandler
- (void)handleTap {
    NSLog(@"GOX: Button tapped, viewID=%d", self.viewID);
    GoxHandleEvent(self.viewID);

    // Re-render: get new layout from Go and rebuild UI
    if (goxViewController) {
        const char *json = GoxRerender();
        if (json) {
            NSData *data = [NSData dataWithBytes:json length:strlen(json)];
            GoxFreeString(json);

            NSError *error = nil;
            NSArray *frames = [NSJSONSerialization JSONObjectWithData:data options:0 error:&error];
            if (frames && !error) {
                // Remove all existing subviews
                for (UIView *sub in [goxViewController.view.subviews copy]) {
                    [sub removeFromSuperview];
                }
                // Rebuild with new frames
                buildUI(goxViewController, frames);
                NSLog(@"GOX: Re-rendered with %lu frames", (unsigned long)[frames count]);
            }
        }
    }
}
@end

// Keep event handlers alive
static NSMutableArray *goxEventHandlers = nil;

// --- Build UI from flat layout frames ---

static void buildUI(UIViewController *vc, NSArray *frames) {
    // Clear old event handlers
    goxEventHandlers = [NSMutableArray new];
    NSMutableDictionary<NSNumber*, UIView*> *views = [NSMutableDictionary new];

    // Pass 1: Create all views with frames
    for (NSDictionary *frame in frames) {
        int viewID = [frame[@"id"] intValue];
        NSString *tag = frame[@"tag"];
        NSDictionary *props = frame[@"props"];

        double x = [frame[@"x"] doubleValue];
        double y = [frame[@"y"] doubleValue];
        double w = [frame[@"w"] doubleValue];
        double h = [frame[@"h"] doubleValue];

        // Skip fragments and internal text nodes
        if ([tag isEqualToString:@"_fragment"]) {
            // Fragment: create transparent container
            UIView *container = [[UIView alloc] init];
            container.frame = CGRectMake(x, y, w, h);
            views[@(viewID)] = container;
            continue;
        }

        UIView *view = createViewForTag(tag, props);
        view.frame = CGRectMake(x, y, w, h);
        applyVisualStyle(view, props);

        int pid = [frame[@"pid"] intValue];
        NSLog(@"GOX frame: id=%d tag=%@ pid=%d (%.0f,%.0f,%.0f,%.0f)", viewID, tag, pid, x, y, w, h);

        // Handle text content
        NSString *text = frame[@"text"];
        if (text && [text length] > 0) {
            setTextContent(view, text, props);
        }

        // Wire up onPress events for buttons
        NSNumber *hasOnPress = props[@"_hasOnPress"];
        if (hasOnPress && [hasOnPress boolValue]) {
            if ([view isKindOfClass:[UIButton class]]) {
                GoxEventHandler *handler = [[GoxEventHandler alloc] init];
                handler.viewID = viewID;
                [(UIButton *)view addTarget:handler
                                     action:@selector(handleTap)
                           forControlEvents:UIControlEventTouchUpInside];
                [goxEventHandlers addObject:handler]; // prevent dealloc
            }
        }

        views[@(viewID)] = view;
    }

    // Pass 2: Collect text from _text children into parent Text/Button views
    for (NSDictionary *frame in frames) {
        NSString *tag = frame[@"tag"];
        if (![tag isEqualToString:@"_text"]) continue;

        int pid = [frame[@"pid"] intValue];
        NSString *text = frame[@"text"];
        if (!text || pid < 0) continue;

        UIView *parent = views[@(pid)];
        if (parent) {
            // Find the parent frame to get its props for styling
            for (NSDictionary *pf in frames) {
                if ([pf[@"id"] intValue] == pid) {
                    setTextContent(parent, text, pf[@"props"]);
                    break;
                }
            }
        }
    }

    // Pass 3: Build view hierarchy
    for (NSDictionary *frame in frames) {
        int viewID = [frame[@"id"] intValue];
        int pid = [frame[@"pid"] intValue];
        NSString *tag = frame[@"tag"];

        // Skip _text nodes — they're content, not views
        if ([tag isEqualToString:@"_text"]) continue;

        UIView *view = views[@(viewID)];
        if (!view) continue;

        if (pid < 0) {
            // Root view — add directly to view controller
            // Use absolute frame (already computed by Yoga)
            [vc.view addSubview:view];
        } else {
            UIView *parent = views[@(pid)];
            if (parent) {
                // Child frame is absolute, convert to relative to parent
                CGRect childFrame = view.frame;
                CGRect parentFrame = parent.frame;
                view.frame = CGRectMake(
                    childFrame.origin.x - parentFrame.origin.x,
                    childFrame.origin.y - parentFrame.origin.y,
                    childFrame.size.width,
                    childFrame.size.height
                );
                [parent addSubview:view];

                // For ScrollView parents, update content size
                if ([parent isKindOfClass:[UIScrollView class]]) {
                    UIScrollView *sv = (UIScrollView *)parent;
                    CGFloat maxY = CGRectGetMaxY(view.frame);
                    CGFloat maxX = CGRectGetMaxX(view.frame);
                    if (maxY > sv.contentSize.height || maxX > sv.contentSize.width) {
                        sv.contentSize = CGSizeMake(
                            MAX(sv.contentSize.width, maxX),
                            MAX(sv.contentSize.height, maxY)
                        );
                    }
                }
            }
        }
    }
}

// --- App lifecycle ---

@interface GoxAppDelegate : UIResponder <UIApplicationDelegate>
@property (nonatomic, strong) UIWindow *window;
@end

@implementation GoxAppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

    self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
    self.window.backgroundColor = [UIColor whiteColor];

    UIViewController *vc = [[UIViewController alloc] init];
    vc.view.backgroundColor = [UIColor whiteColor];
    self.window.rootViewController = vc;
    [self.window makeKeyAndVisible];

    // Defer layout to next run loop so safeAreaInsets are available
    dispatch_async(dispatch_get_main_queue(), ^{
        [self renderWithViewController:vc];
    });

    return YES;
}

- (void)renderWithViewController:(UIViewController *)vc {
    goxViewController = vc; // save for re-renders
    CGRect screen = [UIScreen mainScreen].bounds;
    UIEdgeInsets safe = self.window.safeAreaInsets;

    NSLog(@"GOX: Screen %.0fx%.0f, safe: t=%.0f r=%.0f b=%.0f l=%.0f",
          screen.size.width, screen.size.height,
          safe.top, safe.right, safe.bottom, safe.left);

    // Call Go layout engine
    const char *json = GoxGetLayout(
        screen.size.width, screen.size.height,
        safe.top, safe.right, safe.bottom, safe.left
    );

    if (!json) {
        NSLog(@"GOX: GoxGetLayout returned null");
        return;
    }

    NSData *data = [NSData dataWithBytes:json length:strlen(json)];
    GoxFreeString(json);

    NSError *error = nil;
    NSArray *frames = [NSJSONSerialization JSONObjectWithData:data options:0 error:&error];

    if (error || ![frames isKindOfClass:[NSArray class]]) {
        NSLog(@"GOX: JSON parse error: %@", error);
        return;
    }

    NSLog(@"GOX: Building UI from %lu frames", (unsigned long)[frames count]);
    buildUI(vc, frames);
}

@end

int main(int argc, char * argv[]) {
    @autoreleasepool {
        return UIApplicationMain(argc, argv, nil, NSStringFromClass([GoxAppDelegate class]));
    }
}
