// bridge_core.m — GOX iOS bridge implementation (component registry architecture)
// Auto-generated by gox. Do not edit.
//
// Architecture:
//   1. AppDelegate gets screen dimensions + safe area insets
//   2. Calls GoxGetLayout() (exported from Go) with screen info
//   3. Go runs Yoga layout engine, returns flat array of positioned frames
//   4. This code creates UIKit views and positions them with view.frame
//   5. Re-renders diff against previous frames — only updates what changed
//   6. Navigation: UINavigationController with context stack for push/pop
//   7. Components register via GoxComponentDef structs at load time
//
// No UIStackView. No Auto Layout. All layout is computed by Yoga in Go.

#import <UIKit/UIKit.h>
#import <QuartzCore/QuartzCore.h>
#import <mach/mach.h>

// Exported from the Go static library
extern const char* GoxGetLayout(double w, double h, double safeT, double safeR, double safeB, double safeL);
extern void GoxHandleEvent(int viewID);
extern const char* GoxRerender(void);
extern void GoxFreeString(const char* s);
extern void GoxHandleBack(void);
extern void GoxAppDidEnterForeground(void);
extern void GoxAppDidEnterBackground(void);

// --- Component registry ---

@class GoxEventHandler;
@class GoxRenderContext;

typedef struct {
    const char *tag;
    UIView* (*createView)(NSDictionary *props);
    void (*applyStyle)(UIView *view, NSDictionary *props);
    void (*setContent)(UIView *view, NSString *text, NSDictionary *props);
    void (*wireEvent)(UIView *view, int viewID, GoxRenderContext *ctx);
    void (*updateView)(UIView *view, NSDictionary *oldProps, NSDictionary *newProps);
    void (*childAdded)(UIView *parent, UIView *child, CGRect childFrame);
} GoxComponentDef;

static GoxComponentDef goxComponents[64];
static int goxComponentCount = 0;

GoxComponentDef* goxGetComponent(NSString *tag) {
    if (!tag) return NULL;
    const char *cTag = [tag UTF8String];
    for (int i = 0; i < goxComponentCount; i++) {
        if (strcmp(goxComponents[i].tag, cTag) == 0) {
            return &goxComponents[i];
        }
    }
    return NULL;
}

void goxRegisterComponent(GoxComponentDef def) {
    if (goxComponentCount < 64) {
        goxComponents[goxComponentCount++] = def;
    }
}

// --- Render context: per-screen state for diffing ---
// Each VC gets its own context. When the VC is deallocated (screen popped),
// all tracked views and state are released automatically via ARC.

@interface GoxRenderContext : NSObject
@property (nonatomic, strong) NSMutableDictionary<NSNumber*, UIView*> *views;
@property (nonatomic, strong) NSMutableDictionary<NSNumber*, NSDictionary*> *framesByID;
@property (nonatomic, strong) NSMutableArray *eventHandlers;
@end

@implementation GoxRenderContext
- (instancetype)init {
    self = [super init];
    if (self) {
        _views = [NSMutableDictionary new];
        _framesByID = [NSMutableDictionary new];
        _eventHandlers = [NSMutableArray new];
    }
    return self;
}

- (void)clear {
    for (UIView *v in [_views allValues]) {
        [v removeFromSuperview];
    }
    [_views removeAllObjects];
    [_framesByID removeAllObjects];
    [_eventHandlers removeAllObjects];
}
@end

// Forward declarations
static void buildUI(UIViewController *vc, GoxRenderContext *ctx, NSArray *frames);
static void updateUI(UIViewController *vc, GoxRenderContext *ctx, NSArray *frames);

// Active render context and navigation state
static GoxRenderContext *goxActiveContext = nil;
static UIViewController *goxViewController = nil;
static UINavigationController *goxNavController = nil;
static NSMutableArray<GoxRenderContext*> *goxContextStack = nil;

// --- Color parsing ---

UIColor* goxParseColor(NSString *hex) {
    if (!hex || [hex length] == 0 || [hex characterAtIndex:0] != '#') {
        return nil;
    }

    NSString *str = [hex substringFromIndex:1];
    unsigned long len = [str length];
    unsigned int r = 0, g = 0, b = 0, a = 255;

    if (len == 3) {
        unsigned int vals[3];
        for (int i = 0; i < 3; i++) {
            NSString *ch = [str substringWithRange:NSMakeRange(i, 1)];
            [[NSScanner scannerWithString:ch] scanHexInt:&vals[i]];
            vals[i] = vals[i] * 17;
        }
        r = vals[0]; g = vals[1]; b = vals[2];
    } else if (len == 6) {
        unsigned int val;
        [[NSScanner scannerWithString:str] scanHexInt:&val];
        r = (val >> 16) & 0xFF;
        g = (val >> 8) & 0xFF;
        b = val & 0xFF;
    } else if (len == 8) {
        unsigned int val;
        [[NSScanner scannerWithString:str] scanHexInt:&val];
        r = (val >> 24) & 0xFF;
        g = (val >> 16) & 0xFF;
        b = (val >> 8) & 0xFF;
        a = val & 0xFF;
    }

    return [UIColor colorWithRed:r/255.0 green:g/255.0 blue:b/255.0 alpha:a/255.0];
}

// --- Image loading helper ---

void goxLoadImageAsync(UIImageView *imageView, NSString *src) {
    if (!src || [src length] == 0) return;
    if ([src hasPrefix:@"http://"] || [src hasPrefix:@"https://"]) {
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
            NSURL *url = [NSURL URLWithString:src];
            NSData *data = [NSData dataWithContentsOfURL:url];
            if (data) {
                UIImage *image = [UIImage imageWithData:data];
                dispatch_async(dispatch_get_main_queue(), ^{
                    imageView.image = image;
                });
            }
        });
    } else {
        imageView.image = [UIImage imageNamed:src];
    }
}

// --- View creation by tag (dispatches to component registry) ---

static UIView* createViewForTag(NSString *tag, NSDictionary *props) {
    GoxComponentDef *comp = goxGetComponent(tag);
    if (comp && comp->createView) {
        return comp->createView(props);
    }
    UIView *v = [[UIView alloc] init];
    v.clipsToBounds = YES;
    return v;
}

// --- Visual style application (no layout — Yoga handles that) ---

void goxApplyUniversalStyle(UIView *view, NSDictionary *props) {
    if (!props) return;

    NSDictionary *style = props[@"style"];
    if (!style) return;

    // Background color
    NSString *bgColor = style[@"BackgroundColor"];
    if (bgColor && [bgColor length] > 0) {
        UIColor *color = goxParseColor(bgColor);
        if (color) view.backgroundColor = color;
    }

    // Opacity
    NSNumber *opacity = style[@"Opacity"];
    if (opacity && [opacity doubleValue] > 0) {
        view.alpha = [opacity doubleValue];
    }

    // Border radius
    NSNumber *borderRadius = style[@"BorderRadius"];
    if (borderRadius && [borderRadius doubleValue] > 0) {
        view.layer.cornerRadius = [borderRadius doubleValue];
        view.clipsToBounds = YES;
    }

    // Border
    NSNumber *borderWidth = style[@"BorderWidth"];
    if (borderWidth && [borderWidth doubleValue] > 0) {
        view.layer.borderWidth = [borderWidth doubleValue];
    }
    NSString *borderColor = style[@"BorderColor"];
    if (borderColor && [borderColor length] > 0) {
        UIColor *bc = goxParseColor(borderColor);
        if (bc) view.layer.borderColor = bc.CGColor;
    }

    // Shadow
    NSString *shadowColor = style[@"ShadowColor"];
    if (shadowColor && [shadowColor length] > 0) {
        UIColor *sc = goxParseColor(shadowColor);
        if (sc) {
            view.layer.shadowColor = sc.CGColor;
            view.layer.shadowOffset = CGSizeMake(
                [style[@"ShadowOffsetX"] doubleValue],
                [style[@"ShadowOffsetY"] doubleValue]
            );
            view.layer.shadowRadius = [style[@"ShadowRadius"] doubleValue];
            view.layer.shadowOpacity = [style[@"ShadowOpacity"] floatValue];
        }
    }
}

static void applyVisualStyle(UIView *view, NSString *tag, NSDictionary *props) {
    goxApplyUniversalStyle(view, props);

    GoxComponentDef *comp = goxGetComponent(tag);
    if (comp && comp->applyStyle) {
        comp->applyStyle(view, props);
    }
}

// --- Set text content on a view (dispatches to component registry) ---

static void setTextContent(UIView *view, NSString *tag, NSString *text, NSDictionary *props) {
    GoxComponentDef *comp = goxGetComponent(tag);
    if (comp && comp->setContent) {
        comp->setContent(view, text, props);
    }
}

// --- Wire event handler (dispatches to component registry) ---

static void wireEvent(UIView *view, NSString *tag, int viewID, GoxRenderContext *ctx) {
    GoxComponentDef *comp = goxGetComponent(tag);
    if (comp && comp->wireEvent) {
        comp->wireEvent(view, viewID, ctx);
    }
}

// --- Performance monitor overlay ---

static double goxLastGoMs = 0;
static double goxLastBridgeMs = 0;
static int goxLastChangedFrames = 0;
static int goxLastTotalFrames = 0;

static double getMemoryMB(void) {
    struct mach_task_basic_info info;
    mach_msg_type_number_t count = MACH_TASK_BASIC_INFO_COUNT;
    if (task_info(mach_task_self(), MACH_TASK_BASIC_INFO, (task_info_t)&info, &count) == KERN_SUCCESS) {
        return info.resident_size / (1024.0 * 1024.0);
    }
    return 0;
}

// Parse JSON response — detects bare array, perf-wrapped object, or nav action.
// Returns the frames array and optionally extracts perf data, navigation action, and nav options.
static NSArray* parseGoxResponse(NSData *data, NSDictionary **outPerf, NSString **outAction, NSDictionary **outNav) {
    NSError *error = nil;
    id parsed = [NSJSONSerialization JSONObjectWithData:data options:0 error:&error];
    if (error || !parsed) return nil;

    if ([parsed isKindOfClass:[NSArray class]]) {
        if (outPerf) *outPerf = nil;
        if (outAction) *outAction = nil;
        if (outNav) *outNav = nil;
        return parsed;
    }
    if ([parsed isKindOfClass:[NSDictionary class]]) {
        if (outPerf) *outPerf = parsed[@"perf"];
        if (outAction) *outAction = parsed[@"action"];
        if (outNav) *outNav = parsed[@"nav"];
        NSArray *frames = parsed[@"frames"];
        if ([frames isKindOfClass:[NSArray class]]) return frames;
    }
    return nil;
}

// --- Bar button handler for nav bar items ---

@interface GoxBarButtonHandler : NSObject
@property (nonatomic, assign) int eventID;
- (void)handleTap;
@end

@implementation GoxBarButtonHandler
- (void)handleTap {
    GoxHandleEvent(self.eventID);
    if (goxViewController && goxActiveContext) {
        const char *json = GoxRerender();
        if (json) {
            NSData *data = [NSData dataWithBytes:json length:strlen(json)];
            GoxFreeString(json);
            NSDictionary *perfData = nil;
            NSString *navAction = nil;
            NSDictionary *navOpts = nil;
            NSArray *frames = parseGoxResponse(data, &perfData, &navAction, &navOpts);
            if (frames) {
                CFTimeInterval bridgeStart = CACurrentMediaTime();
                updateUI(goxViewController, goxActiveContext, frames);
                goxLastBridgeMs = (CACurrentMediaTime() - bridgeStart) * 1000.0;
            }
        }
    }
}
@end

// Retained handlers to prevent ARC deallocation
static NSMutableArray *goxBarButtonHandlers = nil;

static UIBarButtonItem* createBarButtonItem(NSDictionary *btnDict) {
    int eventID = [btnDict[@"eventID"] intValue];

    GoxBarButtonHandler *handler = [[GoxBarButtonHandler alloc] init];
    handler.eventID = eventID;
    if (!goxBarButtonHandlers) goxBarButtonHandlers = [NSMutableArray new];
    [goxBarButtonHandlers addObject:handler];

    NSString *systemItem = btnDict[@"systemItem"];
    if (systemItem && [systemItem length] > 0) {
        UIBarButtonSystemItem item = UIBarButtonSystemItemDone;
        if ([systemItem isEqualToString:@"done"]) item = UIBarButtonSystemItemDone;
        else if ([systemItem isEqualToString:@"cancel"]) item = UIBarButtonSystemItemCancel;
        else if ([systemItem isEqualToString:@"edit"]) item = UIBarButtonSystemItemEdit;
        else if ([systemItem isEqualToString:@"add"]) item = UIBarButtonSystemItemAdd;
        else if ([systemItem isEqualToString:@"close"]) item = UIBarButtonSystemItemClose;
        else if ([systemItem isEqualToString:@"search"]) item = UIBarButtonSystemItemSearch;
        else if ([systemItem isEqualToString:@"compose"]) item = UIBarButtonSystemItemCompose;

        return [[UIBarButtonItem alloc] initWithBarButtonSystemItem:item
                                                            target:handler
                                                            action:@selector(handleTap)];
    }

    NSString *title = btnDict[@"title"];
    return [[UIBarButtonItem alloc] initWithTitle:(title ?: @"")
                                            style:UIBarButtonItemStylePlain
                                           target:handler
                                           action:@selector(handleTap)];
}

// Apply navigation options to a view controller
static void applyNavOptions(UIViewController *vc, NSDictionary *navOpts, UINavigationController *navCtrl) {
    if (!navOpts || ![navOpts isKindOfClass:[NSDictionary class]]) return;

    // Title
    NSString *title = navOpts[@"title"];
    if (title && [title length] > 0) {
        vc.title = title;
    }

    // Large title
    NSNumber *largeTitle = navOpts[@"largeTitle"];
    if (largeTitle) {
        if ([largeTitle boolValue]) {
            navCtrl.navigationBar.prefersLargeTitles = YES;
            vc.navigationItem.largeTitleDisplayMode = UINavigationItemLargeTitleDisplayModeAlways;
        } else {
            vc.navigationItem.largeTitleDisplayMode = UINavigationItemLargeTitleDisplayModeNever;
        }
    }

    // Back button title (for the NEXT screen's back button)
    NSString *backTitle = navOpts[@"backTitle"];
    if (backTitle) {
        vc.navigationItem.backButtonTitle = backTitle;
    }

    // Back button visibility
    NSNumber *backVisible = navOpts[@"backVisible"];
    if (backVisible && ![backVisible boolValue]) {
        vc.navigationItem.hidesBackButton = YES;
    }

    // Gesture enabled
    NSNumber *gestureEnabled = navOpts[@"gestureEnabled"];
    if (gestureEnabled && navCtrl) {
        navCtrl.interactivePopGestureRecognizer.enabled = [gestureEnabled boolValue];
    }

    // Header style
    NSDictionary *headerStyle = navOpts[@"headerStyle"];
    if (headerStyle) {
        UINavigationBarAppearance *appearance = [[UINavigationBarAppearance alloc] init];
        [appearance configureWithOpaqueBackground];

        NSString *bgColor = headerStyle[@"backgroundColor"];
        if (bgColor && [bgColor length] > 0) {
            appearance.backgroundColor = goxParseColor(bgColor);
        }

        NSString *titleColor = headerStyle[@"titleColor"];
        if (titleColor && [titleColor length] > 0) {
            UIColor *tc = goxParseColor(titleColor);
            appearance.titleTextAttributes = @{NSForegroundColorAttributeName: tc};
            appearance.largeTitleTextAttributes = @{NSForegroundColorAttributeName: tc};
        }

        vc.navigationItem.standardAppearance = appearance;
        vc.navigationItem.scrollEdgeAppearance = appearance;
        vc.navigationItem.compactAppearance = appearance;

        NSString *tintColor = headerStyle[@"tintColor"];
        if (tintColor && [tintColor length] > 0) {
            navCtrl.navigationBar.tintColor = goxParseColor(tintColor);
        }
    }

    // Clear previous bar button handlers
    [goxBarButtonHandlers removeAllObjects];

    // Right bar buttons
    NSArray *rightButtons = navOpts[@"rightButtons"];
    if (rightButtons && [rightButtons count] > 0) {
        NSMutableArray *items = [NSMutableArray new];
        for (NSDictionary *btn in rightButtons) {
            UIBarButtonItem *item = createBarButtonItem(btn);
            if (item) [items addObject:item];
        }
        vc.navigationItem.rightBarButtonItems = items;
    }

    // Left bar buttons
    NSArray *leftButtons = navOpts[@"leftButtons"];
    if (leftButtons && [leftButtons count] > 0) {
        NSMutableArray *items = [NSMutableArray new];
        for (NSDictionary *btn in leftButtons) {
            UIBarButtonItem *item = createBarButtonItem(btn);
            if (item) [items addObject:item];
        }
        vc.navigationItem.leftBarButtonItems = items;
    }
}

@interface GoxPerfOverlay : NSObject
@property (nonatomic, strong) UIWindow *overlayWindow;
@property (nonatomic, strong) UILabel *line1;
@property (nonatomic, strong) UILabel *line2;
@property (nonatomic, strong) UILabel *line3;
@property (nonatomic, strong) CADisplayLink *displayLink;
@property (nonatomic, assign) CFTimeInterval lastTimestamp;
@property (nonatomic, assign) int frameCount;
+ (instancetype)shared;
- (void)show;
- (void)hide;
- (void)tick:(CADisplayLink *)link;
@end

static GoxPerfOverlay *goxPerfOverlay = nil;

@implementation GoxPerfOverlay

+ (instancetype)shared {
    if (!goxPerfOverlay) {
        goxPerfOverlay = [[GoxPerfOverlay alloc] init];
    }
    return goxPerfOverlay;
}

- (void)show {
    if (self.overlayWindow) return;

    CGFloat w = 230, h = 58;
    UIEdgeInsets safe = UIEdgeInsetsZero;
    for (UIWindowScene *scene in UIApplication.sharedApplication.connectedScenes) {
        if ([scene isKindOfClass:[UIWindowScene class]]) {
            safe = scene.windows.firstObject.safeAreaInsets;
            break;
        }
    }

    self.overlayWindow = [[UIWindow alloc] initWithFrame:CGRectMake(8, safe.top + 4, w, h)];
    self.overlayWindow.windowLevel = UIWindowLevelStatusBar + 100;
    self.overlayWindow.backgroundColor = [UIColor colorWithRed:0 green:0 blue:0 alpha:0.82];
    self.overlayWindow.layer.cornerRadius = 8;
    self.overlayWindow.clipsToBounds = YES;
    self.overlayWindow.hidden = NO;

    // Make draggable
    UIPanGestureRecognizer *pan = [[UIPanGestureRecognizer alloc]
        initWithTarget:self action:@selector(handleDrag:)];
    [self.overlayWindow addGestureRecognizer:pan];

    UIFont *font = [UIFont monospacedSystemFontOfSize:10.5 weight:UIFontWeightMedium];
    UIColor *green = [UIColor colorWithRed:0.3 green:1.0 blue:0.3 alpha:1.0];

    self.line1 = [self makeLabelWithFont:font color:green y:4];
    self.line2 = [self makeLabelWithFont:font color:green y:22];
    self.line3 = [self makeLabelWithFont:font color:green y:38];

    self.line1.text = @" FPS: --";
    self.line2.text = @" Go: --   Bridge: --";
    self.line3.text = @" Mem: --   Views: --";

    self.displayLink = [CADisplayLink displayLinkWithTarget:self selector:@selector(tick:)];
    [self.displayLink addToRunLoop:[NSRunLoop mainRunLoop] forMode:NSRunLoopCommonModes];
    self.lastTimestamp = 0;
    self.frameCount = 0;
}

- (void)hide {
    [self.displayLink invalidate];
    self.displayLink = nil;
    self.overlayWindow.hidden = YES;
    self.overlayWindow = nil;
}

- (UILabel *)makeLabelWithFont:(UIFont *)font color:(UIColor *)color y:(CGFloat)y {
    UILabel *label = [[UILabel alloc] initWithFrame:CGRectMake(0, y, 230, 16)];
    label.font = font;
    label.textColor = color;
    label.backgroundColor = [UIColor clearColor];
    [self.overlayWindow addSubview:label];
    return label;
}

- (void)handleDrag:(UIPanGestureRecognizer *)pan {
    if (pan.state != UIGestureRecognizerStateChanged) return;

    CGPoint translation = [pan translationInView:self.overlayWindow];
    CGRect frame = self.overlayWindow.frame;
    frame.origin.x += translation.x;
    frame.origin.y += translation.y;

    // Clamp to screen bounds
    CGRect screen = [UIScreen mainScreen].bounds;
    if (frame.origin.x < 0) frame.origin.x = 0;
    if (frame.origin.y < 0) frame.origin.y = 0;
    if (CGRectGetMaxX(frame) > screen.size.width)
        frame.origin.x = screen.size.width - frame.size.width;
    if (CGRectGetMaxY(frame) > screen.size.height)
        frame.origin.y = screen.size.height - frame.size.height;

    self.overlayWindow.frame = frame;
    [pan setTranslation:CGPointZero inView:self.overlayWindow];
}

- (void)tick:(CADisplayLink *)link {
    self.frameCount++;

    CFTimeInterval now = CACurrentMediaTime();
    if (self.lastTimestamp == 0) {
        self.lastTimestamp = now;
        return;
    }

    CFTimeInterval elapsed = now - self.lastTimestamp;
    if (elapsed >= 0.5) {
        double fps = self.frameCount / elapsed;
        self.frameCount = 0;
        self.lastTimestamp = now;

        int viewCount = goxActiveContext ? (int)[goxActiveContext.views count] : 0;

        self.line1.text = [NSString stringWithFormat:@" FPS: %.0f    Frames: %d/%d",
                           fps, goxLastChangedFrames, goxLastTotalFrames];
        self.line2.text = [NSString stringWithFormat:@" Go: %.1fms   Bridge: %.1fms",
                           goxLastGoMs, goxLastBridgeMs];
        self.line3.text = [NSString stringWithFormat:@" Mem: %.1f MB   Views: %d",
                           getMemoryMB(), viewCount];
    }
}

@end

// --- Event handling ---

@interface GoxEventHandler : NSObject
@property (nonatomic, assign) int viewID;
- (void)handleTap;
@end

@implementation GoxEventHandler
- (void)handleTap {
    NSLog(@"GOX_INTERNAL: Button tapped, viewID=%d", self.viewID);
    GoxHandleEvent(self.viewID);

    // Re-render: get new layout from Go and diff-update
    if (goxViewController && goxActiveContext) {
        const char *json = GoxRerender();
        if (json) {
            NSData *data = [NSData dataWithBytes:json length:strlen(json)];
            GoxFreeString(json);

            NSDictionary *perfData = nil;
            NSString *navAction = nil;
            NSDictionary *navOpts = nil;
            NSArray *frames = parseGoxResponse(data, &perfData, &navAction, &navOpts);
            if (frames) {
                // Extract Go timing if perf is enabled
                if (perfData) {
                    double renderNs = [perfData[@"renderNs"] doubleValue];
                    double layoutNs = [perfData[@"layoutNs"] doubleValue];
                    double marshalNs = [perfData[@"marshalNs"] doubleValue];
                    goxLastGoMs = (renderNs + layoutNs + marshalNs) / 1e6;
                    goxLastTotalFrames = [perfData[@"frameCount"] intValue];
                }

                // Handle navigation actions
                if ([navAction isEqualToString:@"push"]) {
                    NSLog(@"GOX_INTERNAL: Pushing new screen");

                    // Create new VC and context for the pushed screen
                    UIViewController *newVC = [[UIViewController alloc] init];
                    newVC.view.backgroundColor = [UIColor whiteColor];

                    // Apply navigation options (title, style, buttons, etc.)
                    applyNavOptions(newVC, navOpts, goxNavController);

                    GoxRenderContext *newCtx = [[GoxRenderContext alloc] init];

                    // Push context onto stack
                    [goxContextStack addObject:newCtx];

                    // Build UI on the new VC
                    CFTimeInterval bridgeStart = CACurrentMediaTime();
                    buildUI(newVC, newCtx, frames);
                    goxLastBridgeMs = (CACurrentMediaTime() - bridgeStart) * 1000.0;

                    // Switch active state
                    goxViewController = newVC;
                    goxActiveContext = newCtx;

                    // Show/hide nav bar based on headerShown option
                    BOOL headerShown = YES;
                    if (navOpts && navOpts[@"headerShown"]) {
                        headerShown = [navOpts[@"headerShown"] boolValue];
                    }
                    [goxNavController setNavigationBarHidden:!headerShown animated:NO];
                    [goxNavController pushViewController:newVC animated:YES];

                    NSLog(@"GOX_INTERNAL: Pushed screen with %lu frames", (unsigned long)[frames count]);
                } else if ([navAction isEqualToString:@"pop"]) {
                    NSLog(@"GOX_INTERNAL: Popping screen");

                    // Pop the current context
                    if ([goxContextStack count] > 1) {
                        [goxContextStack removeLastObject];

                        // Hide nav bar if returning to root
                        if ([goxContextStack count] <= 1) {
                            [goxNavController setNavigationBarHidden:YES animated:YES];
                        }

                        // Pop with native iOS animation
                        [goxNavController popViewControllerAnimated:YES];

                        // Restore previous context
                        goxActiveContext = [goxContextStack lastObject];
                        goxViewController = goxNavController.topViewController;

                        // Re-render to re-register event callbacks on restored screen
                        const char *reJson = GoxRerender();
                        if (reJson) {
                            NSData *reData = [NSData dataWithBytes:reJson length:strlen(reJson)];
                            GoxFreeString(reJson);

                            NSDictionary *rePerfData = nil;
                            NSString *reAction = nil;
                            NSDictionary *reNav = nil;
                            NSArray *reFrames = parseGoxResponse(reData, &rePerfData, &reAction, &reNav);
                            if (reFrames) {
                                CFTimeInterval bridgeStart = CACurrentMediaTime();
                                updateUI(goxViewController, goxActiveContext, reFrames);
                                goxLastBridgeMs = (CACurrentMediaTime() - bridgeStart) * 1000.0;
                            }
                        }

                        NSLog(@"GOX_INTERNAL: Popped to previous screen");
                    }
                } else {
                    // Normal re-render (no navigation)
                    CFTimeInterval bridgeStart = CACurrentMediaTime();
                    updateUI(goxViewController, goxActiveContext, frames);
                    goxLastBridgeMs = (CACurrentMediaTime() - bridgeStart) * 1000.0;
                }

                NSLog(@"GOX_INTERNAL: Updated %lu frames", (unsigned long)[frames count]);
            }
        }
    }
}
@end

// --- Initial build: creates all views from scratch ---

static void buildUI(UIViewController *vc, GoxRenderContext *ctx, NSArray *frames) {
    [ctx clear];

    NSMutableDictionary<NSNumber*, NSValue*> *absFrames = [NSMutableDictionary new];
    NSMutableDictionary<NSNumber*, NSString*> *tagsByID = [NSMutableDictionary new];

    // Pass 1: Create all views with absolute frames
    for (NSDictionary *frame in frames) {
        int viewID = [frame[@"id"] intValue];
        NSString *tag = frame[@"tag"];
        NSDictionary *props = frame[@"props"];

        double x = [frame[@"x"] doubleValue];
        double y = [frame[@"y"] doubleValue];
        double w = [frame[@"w"] doubleValue];
        double h = [frame[@"h"] doubleValue];

        CGRect absRect = CGRectMake(x, y, w, h);
        absFrames[@(viewID)] = [NSValue valueWithCGRect:absRect];
        tagsByID[@(viewID)] = tag;

        if ([tag isEqualToString:@"_text"]) continue;

        if ([tag isEqualToString:@"_fragment"]) {
            UIView *container = [[UIView alloc] init];
            container.frame = absRect;
            ctx.views[@(viewID)] = container;
            continue;
        }

        UIView *view = createViewForTag(tag, props);
        view.frame = absRect;
        applyVisualStyle(view, tag, props);

        NSString *text = frame[@"text"];
        if (text && [text length] > 0) {
            setTextContent(view, tag, text, props);
        }

        NSNumber *hasOnPress = props[@"_hasOnPress"];
        if (hasOnPress && [hasOnPress boolValue]) {
            wireEvent(view, tag, viewID, ctx);
        }

        ctx.views[@(viewID)] = view;
    }

    // Pass 2: Merge _text children into parent Text/Button views
    for (NSDictionary *frame in frames) {
        NSString *tag = frame[@"tag"];
        if (![tag isEqualToString:@"_text"]) continue;

        int pid = [frame[@"pid"] intValue];
        NSString *text = frame[@"text"];
        if (!text || pid < 0) continue;

        UIView *parent = ctx.views[@(pid)];
        if (parent) {
            NSString *parentTag = tagsByID[@(pid)];
            for (NSDictionary *pf in frames) {
                if ([pf[@"id"] intValue] == pid) {
                    setTextContent(parent, parentTag, text, pf[@"props"]);
                    break;
                }
            }
        }
    }

    // Pass 3: Build view hierarchy using absolute frames for coordinate conversion
    for (NSDictionary *frame in frames) {
        int viewID = [frame[@"id"] intValue];
        int pid = [frame[@"pid"] intValue];
        NSString *tag = frame[@"tag"];

        if ([tag isEqualToString:@"_text"]) continue;

        UIView *view = ctx.views[@(viewID)];
        if (!view) continue;

        if (pid < 0) {
            [vc.view addSubview:view];
        } else {
            UIView *parent = ctx.views[@(pid)];
            if (parent) {
                CGRect childAbs = [absFrames[@(viewID)] CGRectValue];
                CGRect parentAbs = [absFrames[@(pid)] CGRectValue];
                view.frame = CGRectMake(
                    childAbs.origin.x - parentAbs.origin.x,
                    childAbs.origin.y - parentAbs.origin.y,
                    childAbs.size.width,
                    childAbs.size.height
                );

                // Disable touch on non-interactive children of buttons
                // so taps pass through to the UIButton
                if ([parent isKindOfClass:[UIButton class]] &&
                    ![view isKindOfClass:[UIButton class]] &&
                    ![view isKindOfClass:[UITextField class]] &&
                    ![view isKindOfClass:[UISwitch class]]) {
                    view.userInteractionEnabled = NO;
                }

                [parent addSubview:view];

                NSString *parentTag = tagsByID[@(pid)];
                GoxComponentDef *parentComp = goxGetComponent(parentTag);
                if (parentComp && parentComp->childAdded) {
                    parentComp->childAdded(parent, view, view.frame);
                }
            }
        }
    }

    // Save frame data for future diffs
    for (NSDictionary *frame in frames) {
        ctx.framesByID[frame[@"id"]] = frame;
    }
}

// --- Diff-based update: only changes what's different ---

static void updateUI(UIViewController *vc, GoxRenderContext *ctx, NSArray *newFrames) {
    int changedCount = 0;

    // Build ID set for deletion detection
    NSMutableSet<NSNumber*> *newIDSet = [NSMutableSet new];
    for (NSDictionary *f in newFrames) {
        [newIDSet addObject:f[@"id"]];
    }

    // Reset event handlers (Go clears callbacks each render)
    ctx.eventHandlers = [NSMutableArray new];

    // Absolute frames for coordinate conversion
    NSMutableDictionary<NSNumber*, NSValue*> *absFrames = [NSMutableDictionary new];

    // Index new frames by parent for _text merging
    NSMutableDictionary<NSNumber*, NSDictionary*> *newFrameByID = [NSMutableDictionary new];
    for (NSDictionary *f in newFrames) {
        newFrameByID[f[@"id"]] = f;
    }

    // Pass 1: Update/create views + merge _text in one pass
    for (NSDictionary *frame in newFrames) {
        NSNumber *viewID = frame[@"id"];
        NSString *tag = frame[@"tag"];
        NSDictionary *props = frame[@"props"];

        double x = [frame[@"x"] doubleValue];
        double y = [frame[@"y"] doubleValue];
        double w = [frame[@"w"] doubleValue];
        double h = [frame[@"h"] doubleValue];
        CGRect absRect = CGRectMake(x, y, w, h);
        absFrames[viewID] = [NSValue valueWithCGRect:absRect];

        // Handle _text nodes: merge into parent if changed
        if ([tag isEqualToString:@"_text"]) {
            int pid = [frame[@"pid"] intValue];
            NSString *text = frame[@"text"];
            if (!text || pid < 0) continue;

            NSDictionary *oldFrame = ctx.framesByID[viewID];
            NSString *oldText = oldFrame[@"text"];
            if (![text isEqual:oldText]) {
                UIView *parent = ctx.views[@(pid)];
                if (parent) {
                    NSDictionary *pf = newFrameByID[@(pid)];
                    NSString *parentTag = pf[@"tag"];
                    if (pf) setTextContent(parent, parentTag, text, pf[@"props"]);
                }
            }
            continue;
        }

        UIView *existing = ctx.views[viewID];
        NSDictionary *oldFrame = ctx.framesByID[viewID];

        if (existing && oldFrame) {
            // --- Update existing view ---

            // Hash comparison: skip expensive work if frame is unchanged
            NSString *newHash = frame[@"hash"];
            NSString *oldHash = oldFrame[@"hash"];
            BOOL hashMatch = (newHash && oldHash && [newHash isEqualToString:oldHash]);

            // Tag changed at same ID (structural change) -> recreate
            NSString *oldTag = oldFrame[@"tag"];
            if (![tag isEqualToString:oldTag]) {
                changedCount++;
                [existing removeFromSuperview];
                existing = createViewForTag(tag, props);
                ctx.views[viewID] = existing;
                existing.frame = absRect;
                applyVisualStyle(existing, tag, props);
                NSString *text = frame[@"text"];
                if (text && [text length] > 0) {
                    setTextContent(existing, tag, text, props);
                }
            } else if (!hashMatch) {
                changedCount++;
                // Hash differs — something changed, update style/text
                applyVisualStyle(existing, tag, props);

                // Dispatch to component updateView for tag-specific updates
                GoxComponentDef *comp = goxGetComponent(tag);
                if (comp && comp->updateView) {
                    comp->updateView(existing, oldFrame[@"props"], props);
                }

                // Update text if changed
                NSString *newText = frame[@"text"];
                NSString *oldText = oldFrame[@"text"];
                if (newText && ![newText isEqual:oldText]) {
                    setTextContent(existing, tag, newText, props);
                }
            }
            // else: hash matches — frame unchanged, skip all visual updates
        } else {
            // --- Create new view ---
            changedCount++;
            if ([tag isEqualToString:@"_fragment"]) {
                UIView *container = [[UIView alloc] init];
                container.frame = absRect;
                ctx.views[viewID] = container;
            } else {
                UIView *view = createViewForTag(tag, props);
                view.frame = absRect;
                applyVisualStyle(view, tag, props);
                NSString *text = frame[@"text"];
                if (text && [text length] > 0) {
                    setTextContent(view, tag, text, props);
                }
                ctx.views[viewID] = view;
                existing = view;
            }
        }

        // Re-wire events (must always run — Go clears callbacks each render)
        if (existing) {
            NSNumber *hasOnPress = props[@"_hasOnPress"];
            if (hasOnPress && [hasOnPress boolValue]) {
                wireEvent(existing, tag, [viewID intValue], ctx);
            }
        }
    }

    // Pass 2: Remove views that no longer exist
    for (NSNumber *oldID in [ctx.views allKeys]) {
        if (![newIDSet containsObject:oldID]) {
            UIView *view = ctx.views[oldID];
            [view removeFromSuperview];
            [ctx.views removeObjectForKey:oldID];
        }
    }

    // Pass 3: Fix hierarchy and relative frames
    for (NSDictionary *frame in newFrames) {
        NSNumber *viewID = frame[@"id"];
        int pid = [frame[@"pid"] intValue];
        NSString *tag = frame[@"tag"];

        if ([tag isEqualToString:@"_text"]) continue;

        UIView *view = ctx.views[viewID];
        if (!view) continue;

        CGRect childAbs = [absFrames[viewID] CGRectValue];

        if (pid < 0) {
            view.frame = childAbs;
            if (view.superview != vc.view) {
                [view removeFromSuperview];
                [vc.view addSubview:view];
            }
        } else {
            UIView *parent = ctx.views[@(pid)];
            if (parent) {
                CGRect parentAbs = [absFrames[@(pid)] CGRectValue];
                CGRect relFrame = CGRectMake(
                    childAbs.origin.x - parentAbs.origin.x,
                    childAbs.origin.y - parentAbs.origin.y,
                    childAbs.size.width,
                    childAbs.size.height
                );
                view.frame = relFrame;

                // Disable touch on non-interactive children of buttons
                if ([parent isKindOfClass:[UIButton class]] &&
                    ![view isKindOfClass:[UIButton class]] &&
                    ![view isKindOfClass:[UITextField class]] &&
                    ![view isKindOfClass:[UISwitch class]]) {
                    view.userInteractionEnabled = NO;
                }

                if (view.superview != parent) {
                    [view removeFromSuperview];
                    [parent addSubview:view];
                }

                NSDictionary *parentFrame = newFrameByID[@(pid)];
                NSString *parentTag = parentFrame[@"tag"];
                GoxComponentDef *parentComp = goxGetComponent(parentTag);
                if (parentComp && parentComp->childAdded) {
                    parentComp->childAdded(parent, view, view.frame);
                }
            }
        }
    }

    // Update perf counters
    goxLastChangedFrames = changedCount;

    // Save new frame data for next diff
    [ctx.framesByID removeAllObjects];
    for (NSDictionary *frame in newFrames) {
        ctx.framesByID[frame[@"id"]] = frame;
    }
}

// --- Go-initiated rerender (called from SetState) ---

static BOOL goxRerenderScheduled = NO;

void goxScheduleRerender(void) {
    if (goxRerenderScheduled) return;
    goxRerenderScheduled = YES;
    dispatch_async(dispatch_get_main_queue(), ^{
        goxRerenderScheduled = NO;
        if (!goxViewController || !goxActiveContext) return;

        const char *json = GoxRerender();
        if (!json) return;

        NSData *data = [NSData dataWithBytes:json length:strlen(json)];
        GoxFreeString(json);

        NSDictionary *perfData = nil;
        NSString *navAction = nil;
        NSDictionary *navOpts = nil;
        NSArray *frames = parseGoxResponse(data, &perfData, &navAction, &navOpts);
        if (!frames) return;

        if (perfData) {
            double renderNs = [perfData[@"renderNs"] doubleValue];
            double layoutNs = [perfData[@"layoutNs"] doubleValue];
            double marshalNs = [perfData[@"marshalNs"] doubleValue];
            goxLastGoMs = (renderNs + layoutNs + marshalNs) / 1e6;
            goxLastTotalFrames = [perfData[@"frameCount"] intValue];
        }

        if ([navAction isEqualToString:@"push"]) {
            UIViewController *newVC = [[UIViewController alloc] init];
            newVC.view.backgroundColor = [UIColor whiteColor];
            applyNavOptions(newVC, navOpts, goxNavController);
            GoxRenderContext *newCtx = [[GoxRenderContext alloc] init];
            [goxContextStack addObject:newCtx];
            buildUI(newVC, newCtx, frames);
            goxViewController = newVC;
            goxActiveContext = newCtx;
            BOOL headerShown = YES;
            if (navOpts && navOpts[@"headerShown"]) {
                headerShown = [navOpts[@"headerShown"] boolValue];
            }
            [goxNavController setNavigationBarHidden:!headerShown animated:YES];
            [goxNavController pushViewController:newVC animated:YES];
        } else if ([navAction isEqualToString:@"pop"]) {
            if ([goxContextStack count] > 1) {
                [goxContextStack removeLastObject];
                if ([goxContextStack count] <= 1) {
                    [goxNavController setNavigationBarHidden:YES animated:YES];
                }
                [goxNavController popViewControllerAnimated:YES];
                goxActiveContext = [goxContextStack lastObject];
                goxViewController = goxNavController.topViewController;

                const char *reJson = GoxRerender();
                if (reJson) {
                    NSData *reData = [NSData dataWithBytes:reJson length:strlen(reJson)];
                    GoxFreeString(reJson);
                    NSDictionary *rePerfData = nil;
                    NSString *reAction = nil;
                    NSDictionary *reNav = nil;
                    NSArray *reFrames = parseGoxResponse(reData, &rePerfData, &reAction, &reNav);
                    if (reFrames) {
                        updateUI(goxViewController, goxActiveContext, reFrames);
                    }
                }
            }
        } else {
            CFTimeInterval bridgeStart = CACurrentMediaTime();
            updateUI(goxViewController, goxActiveContext, frames);
            goxLastBridgeMs = (CACurrentMediaTime() - bridgeStart) * 1000.0;
        }
    });
}

// --- App lifecycle ---

@interface GoxAppDelegate : UIResponder <UIApplicationDelegate, UINavigationControllerDelegate>
@property (nonatomic, strong) UIWindow *window;
@end

@implementation GoxAppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

    self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
    self.window.backgroundColor = [UIColor whiteColor];

    UIViewController *rootVC = [[UIViewController alloc] init];
    rootVC.view.backgroundColor = [UIColor whiteColor];

    // Wrap in UINavigationController with hidden nav bar
    goxNavController = [[UINavigationController alloc] initWithRootViewController:rootVC];
    goxNavController.navigationBarHidden = YES;
    goxNavController.delegate = self;

    // Initialize context stack
    goxContextStack = [NSMutableArray new];

    self.window.rootViewController = goxNavController;
    [self.window makeKeyAndVisible];

    // Defer layout to next run loop so safeAreaInsets are available
    dispatch_async(dispatch_get_main_queue(), ^{
        [self renderWithViewController:rootVC];
    });

    return YES;
}

- (void)renderWithViewController:(UIViewController *)vc {
    goxViewController = vc;
    goxActiveContext = [[GoxRenderContext alloc] init];

    // Push root context onto stack
    [goxContextStack addObject:goxActiveContext];

    CGRect screen = [UIScreen mainScreen].bounds;
    UIEdgeInsets safe = self.window.safeAreaInsets;

    NSLog(@"GOX_INTERNAL: Screen %.0fx%.0f, safe: t=%.0f r=%.0f b=%.0f l=%.0f",
          screen.size.width, screen.size.height,
          safe.top, safe.right, safe.bottom, safe.left);

    const char *json = GoxGetLayout(
        screen.size.width, screen.size.height,
        safe.top, safe.right, safe.bottom, safe.left
    );

    if (!json) {
        NSLog(@"GOX_INTERNAL: GoxGetLayout returned null");
        return;
    }

    NSData *data = [NSData dataWithBytes:json length:strlen(json)];
    GoxFreeString(json);

    NSDictionary *perfData = nil;
    NSString *navAction = nil;
    NSDictionary *navOpts = nil;
    NSArray *frames = parseGoxResponse(data, &perfData, &navAction, &navOpts);

    if (!frames) {
        NSLog(@"GOX_INTERNAL: JSON parse error");
        return;
    }

    // Extract Go timing if perf is enabled
    if (perfData) {
        double renderNs = [perfData[@"renderNs"] doubleValue];
        double layoutNs = [perfData[@"layoutNs"] doubleValue];
        double marshalNs = [perfData[@"marshalNs"] doubleValue];
        goxLastGoMs = (renderNs + layoutNs + marshalNs) / 1e6;
        goxLastTotalFrames = [perfData[@"frameCount"] intValue];
        goxLastChangedFrames = goxLastTotalFrames; // initial render = all frames
    }

    NSLog(@"GOX_INTERNAL: Building UI from %lu frames", (unsigned long)[frames count]);

    CFTimeInterval bridgeStart = CACurrentMediaTime();
    buildUI(vc, goxActiveContext, frames);
    goxLastBridgeMs = (CACurrentMediaTime() - bridgeStart) * 1000.0;

    // Show perf overlay if perf data was present
    if (perfData) {
        [[GoxPerfOverlay shared] show];
    }
}

// --- App lifecycle: foreground/background ---

- (void)applicationDidBecomeActive:(UIApplication *)application {
    GoxAppDidEnterForeground();

    // Re-render after returning to foreground
    if (goxViewController && goxActiveContext) {
        const char *json = GoxRerender();
        if (json) {
            NSData *data = [NSData dataWithBytes:json length:strlen(json)];
            GoxFreeString(json);

            NSDictionary *perfData = nil;
            NSString *navAction = nil;
            NSDictionary *navOpts = nil;
            NSArray *frames = parseGoxResponse(data, &perfData, &navAction, &navOpts);
            if (frames) {
                updateUI(goxViewController, goxActiveContext, frames);
            }
        }
    }
}

- (void)applicationDidEnterBackground:(UIApplication *)application {
    GoxAppDidEnterBackground();
}

// --- UINavigationControllerDelegate: detect swipe-back gesture ---

- (void)navigationController:(UINavigationController *)navigationController
       didShowViewController:(UIViewController *)viewController
                    animated:(BOOL)animated {
    // Detect if nav stack shrank (swipe-back or programmatic pop we didn't initiate)
    NSUInteger vcCount = [navigationController.viewControllers count];
    NSUInteger ctxCount = [goxContextStack count];

    if (ctxCount > vcCount) {
        NSLog(@"GOX_INTERNAL: Detected native back (VC count %lu < context count %lu)",
              (unsigned long)vcCount, (unsigned long)ctxCount);

        // Trim context stack to match VC stack
        while ([goxContextStack count] > vcCount) {
            [goxContextStack removeLastObject];
        }

        // Sync Go nav stack
        GoxHandleBack();

        // Hide nav bar if back at root
        if (vcCount <= 1) {
            [navigationController setNavigationBarHidden:YES animated:YES];
        }

        // Restore active context
        goxActiveContext = [goxContextStack lastObject];
        goxViewController = navigationController.topViewController;

        // Re-render to re-register event callbacks on restored screen
        const char *json = GoxRerender();
        if (json) {
            NSData *data = [NSData dataWithBytes:json length:strlen(json)];
            GoxFreeString(json);

            NSDictionary *perfData = nil;
            NSString *navAction = nil;
            NSDictionary *navOpts = nil;
            NSArray *frames = parseGoxResponse(data, &perfData, &navAction, &navOpts);
            if (frames) {
                CFTimeInterval bridgeStart = CACurrentMediaTime();
                updateUI(goxViewController, goxActiveContext, frames);
                goxLastBridgeMs = (CACurrentMediaTime() - bridgeStart) * 1000.0;
            }
        }

        NSLog(@"GOX_INTERNAL: Restored previous screen after swipe-back");
    }
}

@end

int main(int argc, char * argv[]) {
    @autoreleasepool {
        return UIApplicationMain(argc, argv, nil, NSStringFromClass([GoxAppDelegate class]));
    }
}
