// bridge.m — GOX iOS bridge implementation
// Auto-generated by gox. Do not edit.

#import <UIKit/UIKit.h>
#include <stdlib.h>

// --- View registry ---
// Maps integer handles to UIView instances.

static NSMutableDictionary<NSNumber*, UIView*> *viewRegistry = nil;
static long nextHandle = 1;
static UIWindow *mainWindow = nil;

static void ensureRegistry(void) {
    if (!viewRegistry) {
        viewRegistry = [NSMutableDictionary new];
    }
}

static long registerView(UIView *view) {
    ensureRegistry();
    long handle = nextHandle++;
    viewRegistry[@(handle)] = view;
    return handle;
}

static UIView* getView(long handle) {
    ensureRegistry();
    return viewRegistry[@(handle)];
}

// --- Color parsing ---
// Parses hex color strings: "#RGB", "#RRGGBB", "#RRGGBBAA"

static UIColor* parseColor(const char* hex) {
    if (!hex || hex[0] != '#') return [UIColor blackColor];

    NSString *str = [NSString stringWithUTF8String:hex + 1]; // skip #
    unsigned long len = [str length];
    unsigned int r = 0, g = 0, b = 0, a = 255;

    if (len == 3) {
        // #RGB → #RRGGBB
        unsigned int vals[3];
        for (int i = 0; i < 3; i++) {
            NSString *ch = [str substringWithRange:NSMakeRange(i, 1)];
            [[NSScanner scannerWithString:ch] scanHexInt:&vals[i]];
            vals[i] = vals[i] * 17; // 0xF → 0xFF
        }
        r = vals[0]; g = vals[1]; b = vals[2];
    } else if (len == 6) {
        unsigned int val;
        [[NSScanner scannerWithString:str] scanHexInt:&val];
        r = (val >> 16) & 0xFF;
        g = (val >> 8) & 0xFF;
        b = val & 0xFF;
    } else if (len == 8) {
        unsigned int val;
        [[NSScanner scannerWithString:str] scanHexInt:&val];
        r = (val >> 24) & 0xFF;
        g = (val >> 16) & 0xFF;
        b = (val >> 8) & 0xFF;
        a = val & 0xFF;
    }

    return [UIColor colorWithRed:r/255.0 green:g/255.0 blue:b/255.0 alpha:a/255.0];
}

// --- View creation ---

long gox_create_view(void) {
    UIView *view = [[UIView alloc] init];
    view.translatesAutoresizingMaskIntoConstraints = NO;
    return registerView(view);
}

long gox_create_label(const char* text) {
    UILabel *label = [[UILabel alloc] init];
    label.translatesAutoresizingMaskIntoConstraints = NO;
    label.text = [NSString stringWithUTF8String:text];
    label.numberOfLines = 0; // multi-line by default
    return registerView(label);
}

// --- View hierarchy ---

void gox_add_subview(long parent, long child) {
    UIView *parentView = getView(parent);
    UIView *childView = getView(child);
    if (parentView && childView) {
        [parentView addSubview:childView];
    }
}

void gox_set_root_view(long handle) {
    UIView *view = getView(handle);
    if (!view || !mainWindow) return;

    UIViewController *vc = mainWindow.rootViewController;
    if (!vc) {
        vc = [[UIViewController alloc] init];
        mainWindow.rootViewController = vc;
    }

    // Fill safe area
    view.translatesAutoresizingMaskIntoConstraints = NO;
    [vc.view addSubview:view];
    [NSLayoutConstraint activateConstraints:@[
        [view.topAnchor constraintEqualToAnchor:vc.view.safeAreaLayoutGuide.topAnchor],
        [view.bottomAnchor constraintEqualToAnchor:vc.view.safeAreaLayoutGuide.bottomAnchor],
        [view.leadingAnchor constraintEqualToAnchor:vc.view.safeAreaLayoutGuide.leadingAnchor],
        [view.trailingAnchor constraintEqualToAnchor:vc.view.safeAreaLayoutGuide.trailingAnchor],
    ]];
}

// --- Styling ---

void gox_set_background_color(long handle, const char* color) {
    UIView *view = getView(handle);
    if (view) {
        view.backgroundColor = parseColor(color);
    }
}

void gox_set_frame(long handle, double x, double y, double w, double h) {
    UIView *view = getView(handle);
    if (view) {
        view.frame = CGRectMake(x, y, w, h);
    }
}

void gox_set_padding(long handle, double top, double right, double bottom, double left) {
    UIView *view = getView(handle);
    if (view) {
        view.layoutMargins = UIEdgeInsetsMake(top, left, bottom, right);
    }
}

void gox_set_font_size(long handle, double size) {
    UIView *view = getView(handle);
    if ([view isKindOfClass:[UILabel class]]) {
        UILabel *label = (UILabel *)view;
        label.font = [label.font fontWithSize:size];
    }
}

void gox_set_font_weight(long handle, const char* weight) {
    UIView *view = getView(handle);
    if ([view isKindOfClass:[UILabel class]]) {
        UILabel *label = (UILabel *)view;
        CGFloat size = label.font.pointSize;
        NSString *w = [NSString stringWithUTF8String:weight];

        UIFontWeight fontWeight = UIFontWeightRegular;
        if ([w isEqualToString:@"bold"] || [w isEqualToString:@"700"]) {
            fontWeight = UIFontWeightBold;
        } else if ([w isEqualToString:@"600"]) {
            fontWeight = UIFontWeightSemibold;
        } else if ([w isEqualToString:@"500"]) {
            fontWeight = UIFontWeightMedium;
        } else if ([w isEqualToString:@"300"]) {
            fontWeight = UIFontWeightLight;
        } else if ([w isEqualToString:@"100"]) {
            fontWeight = UIFontWeightUltraLight;
        }

        label.font = [UIFont systemFontOfSize:size weight:fontWeight];
    }
}

void gox_set_text_color(long handle, const char* color) {
    UIView *view = getView(handle);
    if ([view isKindOfClass:[UILabel class]]) {
        ((UILabel *)view).textColor = parseColor(color);
    }
}

void gox_set_text_align(long handle, const char* align) {
    UIView *view = getView(handle);
    if ([view isKindOfClass:[UILabel class]]) {
        UILabel *label = (UILabel *)view;
        NSString *a = [NSString stringWithUTF8String:align];

        if ([a isEqualToString:@"center"]) {
            label.textAlignment = NSTextAlignmentCenter;
        } else if ([a isEqualToString:@"right"]) {
            label.textAlignment = NSTextAlignmentRight;
        } else {
            label.textAlignment = NSTextAlignmentLeft;
        }
    }
}

void gox_set_border_radius(long handle, double radius) {
    UIView *view = getView(handle);
    if (view) {
        view.layer.cornerRadius = radius;
        view.clipsToBounds = YES;
    }
}

void gox_set_opacity(long handle, double opacity) {
    UIView *view = getView(handle);
    if (view) {
        view.alpha = opacity;
    }
}

void gox_set_flex_layout(long handle, const char* direction, const char* justify, const char* align) {
    // For MVP, flex layout is handled via UIStackView
    // This is a simplified implementation — full flexbox comes later
    UIView *view = getView(handle);
    if (!view) return;

    // We'll use Auto Layout constraints for basic layout
    // Full flexbox (Yoga) integration is a future enhancement
}

// --- App lifecycle ---

@interface GoxAppDelegate : UIResponder <UIApplicationDelegate>
@property (nonatomic, strong) UIWindow *window;
@end

// Declared in the Go side — called to render the initial view tree
extern void GoxRenderRoot(void);

@implementation GoxAppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

    self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
    self.window.backgroundColor = [UIColor whiteColor];
    self.window.rootViewController = [[UIViewController alloc] init];
    mainWindow = self.window;
    [self.window makeKeyAndVisible];

    // Call into Go to render the view tree
    GoxRenderRoot();

    return YES;
}

@end

void gox_run_app(int argc, char* argv[]) {
    @autoreleasepool {
        UIApplicationMain(argc, argv, nil, NSStringFromClass([GoxAppDelegate class]));
    }
}
