// main.m — GOX iOS entry point
// Auto-generated by gox. Do not edit.

// The actual entry point is in bridge.m via gox_run_app(),
// which is called from Go. This file exists as an Xcode project
// entry point placeholder.
//
// The app lifecycle:
// 1. Go main() calls ios.Backend.RunApp()
// 2. RunApp() calls gox_run_app() in bridge.m
// 3. gox_run_app() calls UIApplicationMain → GoxAppDelegate
// 4. GoxAppDelegate calls GoxRenderRoot() back into Go
// 5. Go renders the node tree via the iOS backend
