package generator

import (
	"fmt"
	"os"
	"path/filepath"
)

// GenerateBootstrap creates the main_gox_bootstrap.go file that
// exports GoxGetLayout and GoxHandleEvent for the iOS bridge.
func GenerateBootstrap(projectDir string, perfEnabled bool) error {
	code := bootstrapCode
	if perfEnabled {
		code = bootstrapCodePerf
	}
	path := filepath.Join(projectDir, "main_gox_bootstrap.go")
	return os.WriteFile(path, []byte(code), 0644)
}

const bootstrapCode = `// Auto-generated by gox. Do not edit.
package main

/*
#include <stdlib.h>
*/
import "C"
import (
	"encoding/json"
	"gox"
	"unsafe"
)

func init() {
	gox.SetRootScreen(func() *gox.Node { return render() })
}

// renderAndLayout renders the current screen and computes layout.
func renderAndLayout(w, h, safeT, safeR, safeB, safeL float64) []byte {
	tree := gox.CurrentScreen()
	if tree == nil {
		return []byte("[]")
	}
	screen := gox.ScreenInfo{
		Width:      w,
		Height:     h,
		SafeTop:    safeT,
		SafeRight:  safeR,
		SafeBottom: safeB,
		SafeLeft:   safeL,
	}
	frames := gox.ComputeLayout(tree, screen)
	framesJSON, err := json.Marshal(frames)
	if err != nil {
		return []byte("[]")
	}

	// Check for pending navigation action
	action := gox.PendingNavAction()
	if action != "" {
		type navResult struct {
			Action string          ` + "`" + `json:"action"` + "`" + `
			Frames json.RawMessage ` + "`" + `json:"frames"` + "`" + `
			Title  string          ` + "`" + `json:"title,omitempty"` + "`" + `
		}
		result := navResult{Action: action, Frames: framesJSON, Title: gox.PendingNavTitle()}
		wrapped, _ := json.Marshal(result)
		return wrapped
	}

	return framesJSON
}

// Saved screen info for re-renders
var savedScreen struct {
	w, h, safeT, safeR, safeB, safeL float64
}

//export GoxGetLayout
func GoxGetLayout(w, h, safeT, safeR, safeB, safeL C.double) *C.char {
	savedScreen.w = float64(w)
	savedScreen.h = float64(h)
	savedScreen.safeT = float64(safeT)
	savedScreen.safeR = float64(safeR)
	savedScreen.safeB = float64(safeB)
	savedScreen.safeL = float64(safeL)

	data := renderAndLayout(float64(w), float64(h),
		float64(safeT), float64(safeR), float64(safeB), float64(safeL))
	return C.CString(string(data))
}

//export GoxHandleEvent
func GoxHandleEvent(viewID C.int) {
	gox.HandleEvent(int(viewID))
}

//export GoxRerender
func GoxRerender() *C.char {
	data := renderAndLayout(
		savedScreen.w, savedScreen.h,
		savedScreen.safeT, savedScreen.safeR,
		savedScreen.safeB, savedScreen.safeL,
	)
	return C.CString(string(data))
}

//export GoxHandleBack
func GoxHandleBack() {
	gox.HandleBack()
}

//export GoxFreeString
func GoxFreeString(s *C.char) {
	C.free(unsafe.Pointer(s))
}

func main() {}
`

const bootstrapCodePerf = `// Auto-generated by gox. Do not edit.
package main

/*
#include <stdlib.h>
*/
import "C"
import (
	"encoding/json"
	"gox"
	"time"
	"unsafe"
)

func init() {
	gox.EnablePerfMonitor()
	gox.SetRootScreen(func() *gox.Node { return render() })
}

// renderAndLayout renders the current screen and computes layout.
func renderAndLayout(w, h, safeT, safeR, safeB, safeL float64) []byte {
	t0 := time.Now()
	tree := gox.CurrentScreen()
	t1 := time.Now()

	if tree == nil {
		return []byte("[]")
	}
	screen := gox.ScreenInfo{
		Width:      w,
		Height:     h,
		SafeTop:    safeT,
		SafeRight:  safeR,
		SafeBottom: safeB,
		SafeLeft:   safeL,
	}
	frames := gox.ComputeLayout(tree, screen)
	t2 := time.Now()

	framesJSON, err := json.Marshal(frames)
	t3 := time.Now()

	if err != nil {
		return []byte("[]")
	}

	perf := gox.PerfData{
		RenderNs:   t1.Sub(t0).Nanoseconds(),
		LayoutNs:   t2.Sub(t1).Nanoseconds(),
		MarshalNs:  t3.Sub(t2).Nanoseconds(),
		FrameCount: len(frames),
	}

	// Check for pending navigation action
	action := gox.PendingNavAction()
	if action != "" {
		type navPerfResult struct {
			Action string          ` + "`" + `json:"action"` + "`" + `
			Frames json.RawMessage ` + "`" + `json:"frames"` + "`" + `
			Perf   gox.PerfData    ` + "`" + `json:"perf"` + "`" + `
			Title  string          ` + "`" + `json:"title,omitempty"` + "`" + `
		}
		result := navPerfResult{Action: action, Frames: framesJSON, Perf: perf, Title: gox.PendingNavTitle()}
		wrapped, _ := json.Marshal(result)
		return wrapped
	}

	// Wrap with perf data
	type perfResult struct {
		Frames json.RawMessage ` + "`" + `json:"frames"` + "`" + `
		Perf   gox.PerfData    ` + "`" + `json:"perf"` + "`" + `
	}
	result := perfResult{Frames: framesJSON, Perf: perf}
	wrapped, _ := json.Marshal(result)
	return wrapped
}

// Saved screen info for re-renders
var savedScreen struct {
	w, h, safeT, safeR, safeB, safeL float64
}

//export GoxGetLayout
func GoxGetLayout(w, h, safeT, safeR, safeB, safeL C.double) *C.char {
	savedScreen.w = float64(w)
	savedScreen.h = float64(h)
	savedScreen.safeT = float64(safeT)
	savedScreen.safeR = float64(safeR)
	savedScreen.safeB = float64(safeB)
	savedScreen.safeL = float64(safeL)

	data := renderAndLayout(float64(w), float64(h),
		float64(safeT), float64(safeR), float64(safeB), float64(safeL))
	return C.CString(string(data))
}

//export GoxHandleEvent
func GoxHandleEvent(viewID C.int) {
	gox.HandleEvent(int(viewID))
}

//export GoxRerender
func GoxRerender() *C.char {
	data := renderAndLayout(
		savedScreen.w, savedScreen.h,
		savedScreen.safeT, savedScreen.safeR,
		savedScreen.safeB, savedScreen.safeL,
	)
	return C.CString(string(data))
}

//export GoxHandleBack
func GoxHandleBack() {
	gox.HandleBack()
}

//export GoxFreeString
func GoxFreeString(s *C.char) {
	C.free(unsafe.Pointer(s))
}

func main() {}
`

// GenerateGoMod creates a go.mod for the test app if one doesn't exist.
func GenerateGoMod(projectDir, moduleName, goxModulePath string) error {
	modPath := filepath.Join(projectDir, "go.mod")
	if _, err := os.Stat(modPath); err == nil {
		return nil
	}

	content := fmt.Sprintf(`module %s

go 1.24

require gox v0.0.0

replace gox => %s
`, moduleName, goxModulePath)

	return os.WriteFile(modPath, []byte(content), 0644)
}
