package generator

import (
	"fmt"
	"os"
	"path/filepath"
)

// GenerateBootstrap creates the main_gox_bootstrap.go file that
// exports GoxGetLayout for the iOS bridge to call.
func GenerateBootstrap(projectDir string) error {
	path := filepath.Join(projectDir, "main_gox_bootstrap.go")
	return os.WriteFile(path, []byte(bootstrapCode), 0644)
}

const bootstrapCode = `// Auto-generated by gox. Do not edit.
package main

/*
#include <stdlib.h>
*/
import "C"
import (
	"encoding/json"
	"gox"
	"unsafe"
)

//export GoxGetLayout
func GoxGetLayout(width, height, safeTop, safeRight, safeBottom, safeLeft C.double) *C.char {
	tree := render()
	if tree == nil {
		return C.CString("[]")
	}
	screen := gox.ScreenInfo{
		Width:      float64(width),
		Height:     float64(height),
		SafeTop:    float64(safeTop),
		SafeRight:  float64(safeRight),
		SafeBottom: float64(safeBottom),
		SafeLeft:   float64(safeLeft),
	}
	frames := gox.ComputeLayout(tree, screen)
	data, err := json.Marshal(frames)
	if err != nil {
		return C.CString("[]")
	}
	return C.CString(string(data))
}

//export GoxFreeString
func GoxFreeString(s *C.char) {
	C.free(unsafe.Pointer(s))
}

func main() {}
`

// GenerateGoMod creates a go.mod for the test app if one doesn't exist.
func GenerateGoMod(projectDir, moduleName, goxModulePath string) error {
	modPath := filepath.Join(projectDir, "go.mod")
	if _, err := os.Stat(modPath); err == nil {
		return nil
	}

	content := fmt.Sprintf(`module %s

go 1.24

require gox v0.0.0

replace gox => %s
`, moduleName, goxModulePath)

	return os.WriteFile(modPath, []byte(content), 0644)
}
