package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GoxImportPath returns the correct import path for the gox package
// based on whether the project uses a replace directive or the real module path.
func GoxImportPath(projectDir string) string {
	data, err := os.ReadFile(filepath.Join(projectDir, "go.mod"))
	if err != nil {
		return "gox"
	}
	if strings.Contains(string(data), "replace gox =>") {
		return "gox"
	}
	if strings.Contains(string(data), "github.com/dreson4/gox") {
		return "github.com/dreson4/gox"
	}
	return "gox"
}

// GenerateBootstrap creates the main_gox_bootstrap.go file that
// exports GoxGetLayout and GoxHandleEvent for the iOS bridge.
func GenerateBootstrap(projectDir string, perfEnabled bool) error {
	code := bootstrapCode
	if perfEnabled {
		code = bootstrapCodePerf
	}
	// Replace gox import path if needed
	importPath := GoxImportPath(projectDir)
	if importPath != "gox" {
		code = strings.Replace(code, `"gox"`, `"`+importPath+`"`, 1)
	}
	path := filepath.Join(projectDir, "main_gox_bootstrap.go")
	return os.WriteFile(path, []byte(code), 0644)
}

const bootstrapCode = `// Auto-generated by gox. Do not edit.
package main

/*
#include <stdlib.h>
extern void goxScheduleRerender(void);
*/
import "C"
import (
	"encoding/json"
	"gox"
	"unsafe"
)

func init() {
	gox.SetRerender(func() {
		C.goxScheduleRerender()
	})
	gox.SetRootScreen(func() *gox.Node { return render() })
}

// renderAndLayout renders the current screen and computes layout.
func renderAndLayout(w, h, safeT, safeR, safeB, safeL float64) []byte {
	tree := gox.CurrentScreen()
	if tree == nil {
		return []byte("[]")
	}
	screen := gox.ScreenInfo{
		Width:      w,
		Height:     h,
		SafeTop:    safeT,
		SafeRight:  safeR,
		SafeBottom: safeB,
		SafeLeft:   safeL,
	}
	frames := gox.ComputeLayout(tree, screen)
	framesJSON, err := json.Marshal(frames)
	if err != nil {
		return []byte("[]")
	}

	gox.FirePendingMount()

	// Check for pending navigation action
	action := gox.PendingNavAction()
	if action != "" {
		type barButtonJSON struct {
			Title      string ` + "`" + `json:"title,omitempty"` + "`" + `
			SystemItem string ` + "`" + `json:"systemItem,omitempty"` + "`" + `
			EventID    int    ` + "`" + `json:"eventID"` + "`" + `
		}
		type headerStyleJSON struct {
			BackgroundColor string ` + "`" + `json:"backgroundColor,omitempty"` + "`" + `
			TintColor       string ` + "`" + `json:"tintColor,omitempty"` + "`" + `
			TitleColor      string ` + "`" + `json:"titleColor,omitempty"` + "`" + `
		}
		type navJSON struct {
			Title          string           ` + "`" + `json:"title,omitempty"` + "`" + `
			LargeTitle     *bool            ` + "`" + `json:"largeTitle,omitempty"` + "`" + `
			HeaderShown    *bool            ` + "`" + `json:"headerShown,omitempty"` + "`" + `
			BackTitle      string           ` + "`" + `json:"backTitle,omitempty"` + "`" + `
			BackVisible    *bool            ` + "`" + `json:"backVisible,omitempty"` + "`" + `
			GestureEnabled *bool            ` + "`" + `json:"gestureEnabled,omitempty"` + "`" + `
			Presentation   string           ` + "`" + `json:"presentation,omitempty"` + "`" + `
			HeaderStyle    *headerStyleJSON ` + "`" + `json:"headerStyle,omitempty"` + "`" + `
			RightButtons   []barButtonJSON  ` + "`" + `json:"rightButtons,omitempty"` + "`" + `
			LeftButtons    []barButtonJSON  ` + "`" + `json:"leftButtons,omitempty"` + "`" + `
		}
		type navResult struct {
			Action string          ` + "`" + `json:"action"` + "`" + `
			Frames json.RawMessage ` + "`" + `json:"frames"` + "`" + `
			Nav    *navJSON        ` + "`" + `json:"nav,omitempty"` + "`" + `
		}
		result := navResult{Action: action, Frames: framesJSON}
		if opts := gox.PendingNavOptions(); opts != nil {
			nj := &navJSON{
				Title:          opts.Title,
				LargeTitle:     opts.LargeTitle,
				HeaderShown:    opts.HeaderShown,
				BackTitle:      opts.BackTitle,
				BackVisible:    opts.BackVisible,
				GestureEnabled: opts.GestureEnabled,
				Presentation:   opts.Presentation,
			}
			if opts.HeaderStyle != nil {
				nj.HeaderStyle = &headerStyleJSON{
					BackgroundColor: opts.HeaderStyle.BackgroundColor,
					TintColor:       opts.HeaderStyle.TintColor,
					TitleColor:      opts.HeaderStyle.TitleColor,
				}
			}
			for _, b := range opts.RightButtons {
				nj.RightButtons = append(nj.RightButtons, barButtonJSON{
					Title: b.Title, SystemItem: b.SystemItem, EventID: b.EventID(),
				})
			}
			for _, b := range opts.LeftButtons {
				nj.LeftButtons = append(nj.LeftButtons, barButtonJSON{
					Title: b.Title, SystemItem: b.SystemItem, EventID: b.EventID(),
				})
			}
			result.Nav = nj
		}
		wrapped, _ := json.Marshal(result)
		return wrapped
	}

	return framesJSON
}

// Saved screen info for re-renders
var savedScreen struct {
	w, h, safeT, safeR, safeB, safeL float64
}

//export GoxGetLayout
func GoxGetLayout(w, h, safeT, safeR, safeB, safeL C.double) *C.char {
	savedScreen.w = float64(w)
	savedScreen.h = float64(h)
	savedScreen.safeT = float64(safeT)
	savedScreen.safeR = float64(safeR)
	savedScreen.safeB = float64(safeB)
	savedScreen.safeL = float64(safeL)

	data := renderAndLayout(float64(w), float64(h),
		float64(safeT), float64(safeR), float64(safeB), float64(safeL))
	return C.CString(string(data))
}

//export GoxHandleEvent
func GoxHandleEvent(viewID C.int) {
	gox.HandleEvent(int(viewID))
}

//export GoxHandleTextEvent
func GoxHandleTextEvent(viewID C.int, text *C.char) {
	gox.HandleTextEvent(int(viewID), C.GoString(text))
}

//export GoxHandleSubmit
func GoxHandleSubmit(viewID C.int) {
	gox.HandleSubmitEvent(int(viewID))
}

//export GoxHandleFocus
func GoxHandleFocus(viewID C.int) {
	gox.HandleFocusEvent(int(viewID))
}

//export GoxHandleBlur
func GoxHandleBlur(viewID C.int) {
	gox.HandleBlurEvent(int(viewID))
}

//export GoxHandleLoad
func GoxHandleLoad(viewID C.int) {
	gox.HandleLoadEvent(int(viewID))
}

//export GoxHandleError
func GoxHandleError(viewID C.int) {
	gox.HandleErrorEvent(int(viewID))
}

//export GoxHandleScroll
func GoxHandleScroll(viewID C.int, offset C.double) {
	gox.HandleScrollEvent(int(viewID), float64(offset))
}

//export GoxHandleScrollEnd
func GoxHandleScrollEnd(viewID C.int) {
	gox.HandleScrollEndEvent(int(viewID))
}

//export GoxRerender
func GoxRerender() *C.char {
	data := renderAndLayout(
		savedScreen.w, savedScreen.h,
		savedScreen.safeT, savedScreen.safeR,
		savedScreen.safeB, savedScreen.safeL,
	)
	return C.CString(string(data))
}

//export GoxHandleBack
func GoxHandleBack() {
	gox.HandleBack()
}

//export GoxAppDidEnterForeground
func GoxAppDidEnterForeground() {
	gox.AppDidEnterForeground()
}

//export GoxAppDidEnterBackground
func GoxAppDidEnterBackground() {
	gox.AppDidEnterBackground()
}

//export GoxFreeString
func GoxFreeString(s *C.char) {
	C.free(unsafe.Pointer(s))
}

func main() {}
`

const bootstrapCodePerf = `// Auto-generated by gox. Do not edit.
package main

/*
#include <stdlib.h>
extern void goxScheduleRerender(void);
*/
import "C"
import (
	"encoding/json"
	"gox"
	"time"
	"unsafe"
)

func init() {
	gox.EnablePerfMonitor()
	gox.SetRerender(func() {
		C.goxScheduleRerender()
	})
	gox.SetRootScreen(func() *gox.Node { return render() })
}

// renderAndLayout renders the current screen and computes layout.
func renderAndLayout(w, h, safeT, safeR, safeB, safeL float64) []byte {
	t0 := time.Now()
	tree := gox.CurrentScreen()
	t1 := time.Now()

	if tree == nil {
		return []byte("[]")
	}
	screen := gox.ScreenInfo{
		Width:      w,
		Height:     h,
		SafeTop:    safeT,
		SafeRight:  safeR,
		SafeBottom: safeB,
		SafeLeft:   safeL,
	}
	frames := gox.ComputeLayout(tree, screen)
	t2 := time.Now()

	framesJSON, err := json.Marshal(frames)
	t3 := time.Now()

	if err != nil {
		return []byte("[]")
	}

	gox.FirePendingMount()

	perf := gox.PerfData{
		RenderNs:   t1.Sub(t0).Nanoseconds(),
		LayoutNs:   t2.Sub(t1).Nanoseconds(),
		MarshalNs:  t3.Sub(t2).Nanoseconds(),
		FrameCount: len(frames),
	}

	// Check for pending navigation action
	action := gox.PendingNavAction()
	if action != "" {
		type barButtonJSON struct {
			Title      string ` + "`" + `json:"title,omitempty"` + "`" + `
			SystemItem string ` + "`" + `json:"systemItem,omitempty"` + "`" + `
			EventID    int    ` + "`" + `json:"eventID"` + "`" + `
		}
		type headerStyleJSON struct {
			BackgroundColor string ` + "`" + `json:"backgroundColor,omitempty"` + "`" + `
			TintColor       string ` + "`" + `json:"tintColor,omitempty"` + "`" + `
			TitleColor      string ` + "`" + `json:"titleColor,omitempty"` + "`" + `
		}
		type navJSON struct {
			Title          string           ` + "`" + `json:"title,omitempty"` + "`" + `
			LargeTitle     *bool            ` + "`" + `json:"largeTitle,omitempty"` + "`" + `
			HeaderShown    *bool            ` + "`" + `json:"headerShown,omitempty"` + "`" + `
			BackTitle      string           ` + "`" + `json:"backTitle,omitempty"` + "`" + `
			BackVisible    *bool            ` + "`" + `json:"backVisible,omitempty"` + "`" + `
			GestureEnabled *bool            ` + "`" + `json:"gestureEnabled,omitempty"` + "`" + `
			Presentation   string           ` + "`" + `json:"presentation,omitempty"` + "`" + `
			HeaderStyle    *headerStyleJSON ` + "`" + `json:"headerStyle,omitempty"` + "`" + `
			RightButtons   []barButtonJSON  ` + "`" + `json:"rightButtons,omitempty"` + "`" + `
			LeftButtons    []barButtonJSON  ` + "`" + `json:"leftButtons,omitempty"` + "`" + `
		}
		type navPerfResult struct {
			Action string          ` + "`" + `json:"action"` + "`" + `
			Frames json.RawMessage ` + "`" + `json:"frames"` + "`" + `
			Perf   gox.PerfData    ` + "`" + `json:"perf"` + "`" + `
			Nav    *navJSON        ` + "`" + `json:"nav,omitempty"` + "`" + `
		}
		result := navPerfResult{Action: action, Frames: framesJSON, Perf: perf}
		if opts := gox.PendingNavOptions(); opts != nil {
			nj := &navJSON{
				Title:          opts.Title,
				LargeTitle:     opts.LargeTitle,
				HeaderShown:    opts.HeaderShown,
				BackTitle:      opts.BackTitle,
				BackVisible:    opts.BackVisible,
				GestureEnabled: opts.GestureEnabled,
				Presentation:   opts.Presentation,
			}
			if opts.HeaderStyle != nil {
				nj.HeaderStyle = &headerStyleJSON{
					BackgroundColor: opts.HeaderStyle.BackgroundColor,
					TintColor:       opts.HeaderStyle.TintColor,
					TitleColor:      opts.HeaderStyle.TitleColor,
				}
			}
			for _, b := range opts.RightButtons {
				nj.RightButtons = append(nj.RightButtons, barButtonJSON{
					Title: b.Title, SystemItem: b.SystemItem, EventID: b.EventID(),
				})
			}
			for _, b := range opts.LeftButtons {
				nj.LeftButtons = append(nj.LeftButtons, barButtonJSON{
					Title: b.Title, SystemItem: b.SystemItem, EventID: b.EventID(),
				})
			}
			result.Nav = nj
		}
		wrapped, _ := json.Marshal(result)
		return wrapped
	}

	// Wrap with perf data
	type perfResult struct {
		Frames json.RawMessage ` + "`" + `json:"frames"` + "`" + `
		Perf   gox.PerfData    ` + "`" + `json:"perf"` + "`" + `
	}
	result := perfResult{Frames: framesJSON, Perf: perf}
	wrapped, _ := json.Marshal(result)
	return wrapped
}

// Saved screen info for re-renders
var savedScreen struct {
	w, h, safeT, safeR, safeB, safeL float64
}

//export GoxGetLayout
func GoxGetLayout(w, h, safeT, safeR, safeB, safeL C.double) *C.char {
	savedScreen.w = float64(w)
	savedScreen.h = float64(h)
	savedScreen.safeT = float64(safeT)
	savedScreen.safeR = float64(safeR)
	savedScreen.safeB = float64(safeB)
	savedScreen.safeL = float64(safeL)

	data := renderAndLayout(float64(w), float64(h),
		float64(safeT), float64(safeR), float64(safeB), float64(safeL))
	return C.CString(string(data))
}

//export GoxHandleEvent
func GoxHandleEvent(viewID C.int) {
	gox.HandleEvent(int(viewID))
}

//export GoxHandleTextEvent
func GoxHandleTextEvent(viewID C.int, text *C.char) {
	gox.HandleTextEvent(int(viewID), C.GoString(text))
}

//export GoxHandleSubmit
func GoxHandleSubmit(viewID C.int) {
	gox.HandleSubmitEvent(int(viewID))
}

//export GoxHandleFocus
func GoxHandleFocus(viewID C.int) {
	gox.HandleFocusEvent(int(viewID))
}

//export GoxHandleBlur
func GoxHandleBlur(viewID C.int) {
	gox.HandleBlurEvent(int(viewID))
}

//export GoxHandleLoad
func GoxHandleLoad(viewID C.int) {
	gox.HandleLoadEvent(int(viewID))
}

//export GoxHandleError
func GoxHandleError(viewID C.int) {
	gox.HandleErrorEvent(int(viewID))
}

//export GoxHandleScroll
func GoxHandleScroll(viewID C.int, offset C.double) {
	gox.HandleScrollEvent(int(viewID), float64(offset))
}

//export GoxHandleScrollEnd
func GoxHandleScrollEnd(viewID C.int) {
	gox.HandleScrollEndEvent(int(viewID))
}

//export GoxRerender
func GoxRerender() *C.char {
	data := renderAndLayout(
		savedScreen.w, savedScreen.h,
		savedScreen.safeT, savedScreen.safeR,
		savedScreen.safeB, savedScreen.safeL,
	)
	return C.CString(string(data))
}

//export GoxHandleBack
func GoxHandleBack() {
	gox.HandleBack()
}

//export GoxAppDidEnterForeground
func GoxAppDidEnterForeground() {
	gox.AppDidEnterForeground()
}

//export GoxAppDidEnterBackground
func GoxAppDidEnterBackground() {
	gox.AppDidEnterBackground()
}

//export GoxFreeString
func GoxFreeString(s *C.char) {
	C.free(unsafe.Pointer(s))
}

func main() {}
`

// GenerateGoMod creates a go.mod for the test app if one doesn't exist.
func GenerateGoMod(projectDir, moduleName, goxModulePath string) error {
	modPath := filepath.Join(projectDir, "go.mod")
	if _, err := os.Stat(modPath); err == nil {
		return nil
	}

	content := fmt.Sprintf(`module %s

go 1.24

require gox v0.0.0

replace gox => %s
`, moduleName, goxModulePath)

	return os.WriteFile(modPath, []byte(content), 0644)
}
